# Curated list of well-known public-domain works to find in PDMX.
# (id, display title, composer key or trad category, title regex, shelf)
import re
def op(o, n=None):
    return rf'\bop(us)?\.?\s*{o}\b' + (rf'[^0-9]{{0,14}}\b{n}\b' if n is not None else '')
def cat(prefix, n): return rf'\b{prefix}\.?\s*{n}\b'
W = []
def add(comp, shelf, rows):
    for r in rows: W.append((r[0], r[1], comp, r[2], shelf))

add('bach', 'Baroque', [
 ('bach-invention-4', 'Invention No. 4 in D minor, BWV 775', cat('bwv',775) + r'|invention (no\.? ?)?4\b'),
 ('bach-invention-8', 'Invention No. 8 in F major, BWV 779', cat('bwv',779) + r'|invention (no\.? ?)?8\b'),
 ('bach-invention-13', 'Invention No. 13 in A minor, BWV 784', cat('bwv',784) + r'|invention (no\.? ?)?13\b'),
 ('bach-invention-14', 'Invention No. 14 in B-flat major, BWV 785', cat('bwv',785)),
 ('bach-invention-2', 'Invention No. 2 in C minor, BWV 773', cat('bwv',773)),
 ('bach-invention-6', 'Invention No. 6 in E major, BWV 777', cat('bwv',777)),
 ('bach-sinfonia-11', 'Sinfonia No. 11 in G minor, BWV 797', cat('bwv',797)),
 ('bach-prelude-c-minor', 'Prelude in C minor, BWV 847', cat('bwv',847) + r'.*prelud|prelud.*' + cat('bwv',847)),
 ('bach-fugue-c-minor', 'Fugue in C minor, BWV 847', r'fug.*' + cat('bwv',847) + '|' + cat('bwv',847) + r'.*fug'),
 ('bach-prelude-d-major', 'Prelude in D major, BWV 850', cat('bwv',850)),
 ('bach-prelude-bwv-999', 'Little Prelude in C minor, BWV 999', cat('bwv',999)),
 ('bach-prelude-bwv-939', 'Little Prelude in C major, BWV 939', cat('bwv',939)),
 ('bach-prelude-bwv-926', 'Little Prelude in D minor, BWV 926', cat('bwv',926)),
 ('bach-prelude-bwv-933', 'Little Prelude in C major, BWV 933', cat('bwv',933)),
 ('bach-prelude-bwv-940', 'Little Prelude in D minor, BWV 940', cat('bwv',940)),
 ('bach-air', 'Air on the G String (Air from Suite No. 3, BWV 1068)', r'air on (the )?g|' + cat('bwv',1068) + r'|\bair\b.*suite (no\.? ?)?3'),
 ('bach-jesu-joy', 'Jesu, Joy of Man’s Desiring, BWV 147', r'jesu,? joy|' + cat('bwv',147)),
 ('bach-toccata-d-minor', 'Toccata and Fugue in D minor, BWV 565', cat('bwv',565) + r'|toccata (and|&) fugue in d'),
 ('bach-cello-suite-1', 'Prelude from Cello Suite No. 1, BWV 1007', cat('bwv',1007) + r'|cello suite'),
 ('bach-sheep-may-safely-graze', 'Sheep May Safely Graze, BWV 208', r'sheep may safely|' + cat('bwv',208)),
 ('bach-badinerie', 'Badinerie from Suite No. 2, BWV 1067', r'badinerie|' + cat('bwv',1067)),
 ('bach-italian-concerto', 'Italian Concerto, BWV 971 · first movement', cat('bwv',971) + r'|italian concerto'),
 ('bach-goldberg-aria', 'Aria from the Goldberg Variations, BWV 988', cat('bwv',988) + r'|goldberg'),
 ('bach-french-suite-5-gavotte', 'Gavotte from French Suite No. 5, BWV 816', cat('bwv',816)),
 ('bach-musette', 'Musette in D major, BWV Anh. 126', r'musette|anh\.? ?126'),
 ('bach-march-d', 'March in D major, BWV Anh. 122', r'anh\.? ?122|march in d major.*bach'),
 ('bach-minuet-g-minor', 'Minuet in G minor, BWV Anh. 115', r'anh\.? ?115|minuet in g minor'),
 ('bach-polonaise-g-minor', 'Polonaise in G minor, BWV Anh. 119', r'anh\.? ?119|polonaise in g minor.*(bach|anh)'),
 ('bach-wachet-auf', 'Sleepers, Wake! (Wachet auf), BWV 645', r'wachet auf|sleepers,? wake|' + cat('bwv',645) + '|' + cat('bwv',140)),
 ('bach-partita-2-sinfonia', 'Sinfonia from Partita No. 2, BWV 826', cat('bwv',826)),
 ('bach-chaconne', 'Chaconne from Partita No. 2 for violin, BWV 1004', cat('bwv',1004) + r'|chaconne.*bach|bach.*chaconne'),
 ('bach-ave-maria', 'Ave Maria (Bach–Gounod)', r'ave maria.*(gounod|bach)|(gounod|bach).*ave maria'),
 ('bach-arioso', 'Arioso, BWV 156', cat('bwv',156) + r'|arioso'),
 ('bach-siciliano', 'Siciliano from Flute Sonata, BWV 1031', cat('bwv',1031) + r'|siciliano.*bach'),
 ('bach-brandenburg-3', 'Brandenburg Concerto No. 3, BWV 1048 · first movement', cat('bwv',1048) + r'|brandenburg'),
])
add('pachelbel', 'Baroque', [('pachelbel-canon', 'Canon in D', r'canon in d|pachelbel.?s canon|^canon\b|\bcanon$')])
add('handel', 'Baroque', [
 ('handel-sarabande', 'Sarabande in D minor, HWV 437', r'sarabande|hwv\.? ?437'),
 ('handel-hallelujah', 'Hallelujah Chorus from Messiah', r'hallelujah.*(messiah|handel)|messiah.*hallelujah|hallelujah chorus'),
 ('handel-largo', 'Largo (Ombra mai fù) from Xerxes', r'ombra mai|largo.*(xerxes|serse)|(xerxes|serse).*largo'),
 ('handel-arrival-queen-sheba', 'Arrival of the Queen of Sheba', r'queen of sheba'),
 ('handel-water-music-hornpipe', 'Hornpipe from Water Music', r'water music'),
 ('handel-passacaglia', 'Passacaglia in G minor (Suite No. 7, HWV 432)', r'passacaglia.*(hwv|handel|g minor)|hwv\.? ?432'),
 ('handel-harmonious-blacksmith', 'The Harmonious Blacksmith', r'harmonious blacksmith|hwv\.? ?430'),
 ('handel-lascia', 'Lascia ch’io pianga', r'lascia ch'),
 ('handel-see-conquering-hero', 'See, the Conquering Hero Comes', r'conquering hero'),
 ('handel-fireworks', 'Music for the Royal Fireworks · La Réjouissance', r'royal fireworks|r[eé]jouissance'),
 ('handel-minuet-g-minor', 'Minuet in G minor, HWV 434', r'hwv\.? ?434|minuet.*handel.*g minor'),
])
add('vivaldi', 'Baroque', [
 ('vivaldi-spring', 'Spring from The Four Seasons · first movement', r'spring|primavera|four seasons|quattro stagioni'),
 ('vivaldi-winter', 'Winter from The Four Seasons · second movement', r'winter|inverno'),
 ('vivaldi-summer', 'Summer from The Four Seasons · third movement', r'summer|estate'),
 ('vivaldi-autumn', 'Autumn from The Four Seasons · first movement', r'autumn|autunno'),
])
add('scarlatti', 'Baroque', [
 ('scarlatti-k141', 'Sonata in D minor, K. 141', cat('k',141) + '|' + cat('l',422)),
 ('scarlatti-k380', 'Sonata in E major, K. 380', cat('k',380)),
 ('scarlatti-k9', 'Sonata in D minor, K. 9 “Pastorale”', cat('k',9) + r'|pastorale'),
 ('scarlatti-k27', 'Sonata in B minor, K. 27', cat('k',27)),
 ('scarlatti-k466', 'Sonata in F minor, K. 466', cat('k',466)),
 ('scarlatti-k1', 'Sonata in D minor, K. 1', cat('k',1)),
])
add('purcell', 'Baroque', [
 ('purcell-rondeau', 'Rondeau from Abdelazer', r'rondeau|abdelazer'),
 ('purcell-trumpet-tune', 'Trumpet Tune', r'trumpet tune'),
 ('purcell-dido-lament', 'Dido’s Lament (When I Am Laid in Earth)', r'dido|when i am laid'),
 ('purcell-minuet', 'Minuet in A minor, Z. 649', r'minuet'),
 ('purcell-hornpipe', 'Hornpipe in E minor', r'hornpipe'),
])
add('rameau', 'Baroque', [
 ('rameau-tambourin', 'Tambourin in E minor', r'tambourin'),
 ('rameau-le-rappel', 'Le Rappel des oiseaux', r'rappel des oiseaux'),
 ('rameau-gavotte', 'Gavotte and Doubles in A minor', r'gavotte'),
 ('rameau-les-sauvages', 'Les Sauvages', r'sauvages'),
])
add('couperin', 'Baroque', [('couperin-barricades', 'Les Barricades mystérieuses', r'barricades'), ('couperin-tic-toc', 'Le Tic-Toc-Choc', r'tic.?toc')])
add('telemann', 'Baroque', [('telemann-fantasia', 'Fantasia in D minor', r'fantasi'), ('telemann-gigue', 'Gigue', r'gigue')])
add('albinoni', 'Baroque', [('albinoni-adagio', 'Adagio in G minor (Albinoni–Giazotto)', r'adagio')])
add('clementi', 'Classical', [
 ('clementi-36-2', 'Sonatina in G, Op. 36 No. 2', op(36, 2)),
 ('clementi-36-3', 'Sonatina in C, Op. 36 No. 3', op(36, 3)),
 ('clementi-36-4', 'Sonatina in F, Op. 36 No. 4', op(36, 4)),
 ('clementi-36-5', 'Sonatina in G, Op. 36 No. 5', op(36, 5)),
 ('clementi-36-6', 'Sonatina in D, Op. 36 No. 6', op(36, 6)),
])
add('haydn', 'Classical', [
 ('haydn-surprise', 'Surprise Symphony (No. 94) · Andante theme', r'surprise'),
 ('haydn-sonata-c-hob16-35', 'Sonata in C, Hob. XVI:35 · first movement', r'xvi[:/ ]?35|hob.*35'),
 ('haydn-sonata-d-hob16-37', 'Sonata in D, Hob. XVI:37 · first movement', r'xvi[:/ ]?37'),
 ('haydn-sonata-e-minor', 'Sonata in E minor, Hob. XVI:34', r'xvi[:/ ]?34'),
 ('haydn-sonata-c-hob16-50', 'Sonata in C, Hob. XVI:50', r'xvi[:/ ]?50'),
 ('haydn-gypsy-rondo', 'Gypsy Rondo', r'gypsy rondo|rondo all.ongarese|hungarian rondo'),
 ('haydn-german-dance', 'German Dance in D', r'german dance'),
 ('haydn-emperor', 'Emperor Hymn (Gott erhalte)', r'emperor|gott erhalte|kaiserhymne'),
 ('haydn-trumpet-concerto', 'Trumpet Concerto · finale', r'trumpet concerto'),
])
add('mozart', 'Classical', [
 ('mozart-k545-2', 'Sonata in C, K. 545 · second movement', cat('k',545) + r'.*(2nd|second|ii\b|andante)'),
 ('mozart-k545-3', 'Sonata in C, K. 545 · third movement', cat('k',545) + r'.*(3rd|third|iii\b|rondo)'),
 ('mozart-k331-1', 'Sonata in A, K. 331 · first movement (theme and variations)', cat('k',331) + r'.*(1st|first|\bi\b|andante grazioso|theme|variation)'),
 ('mozart-k330', 'Sonata in C, K. 330 · first movement', cat('k',330)),
 ('mozart-k332', 'Sonata in F, K. 332 · first movement', cat('k',332)),
 ('mozart-k333', 'Sonata in B-flat, K. 333 · first movement', cat('k',333)),
 ('mozart-k310', 'Sonata in A minor, K. 310 · first movement', cat('k',310)),
 ('mozart-k283', 'Sonata in G, K. 283 · first movement', cat('k',283)),
 ('mozart-k279', 'Sonata in C, K. 279 · first movement', cat('k',279)),
 ('mozart-k457', 'Sonata in C minor, K. 457 · first movement', cat('k',457)),
 ('mozart-k570', 'Sonata in B-flat, K. 570', cat('k',570)),
 ('mozart-k576', 'Sonata in D, K. 576', cat('k',576)),
 ('mozart-fantasia-d-minor', 'Fantasia in D minor, K. 397', cat('k',397) + r'|fantasia in d minor'),
 ('mozart-fantasia-c-minor', 'Fantasia in C minor, K. 475', cat('k',475)),
 ('mozart-twinkle-variations', 'Twelve Variations on “Ah vous dirai-je, Maman”, K. 265', cat('k',265) + r'|ah,? vous dirai'),
 ('mozart-eine-kleine', 'Eine kleine Nachtmusik, K. 525 · first movement', cat('k',525) + r'|kleine nachtmusik|little night music'),
 ('mozart-symphony-40', 'Symphony No. 40 in G minor, K. 550 · first movement', cat('k',550) + r'|symphony (no\.? ?)?40'),
 ('mozart-lacrimosa', 'Lacrimosa from the Requiem, K. 626', r'lacrimosa|' + cat('k',626) + r'|requiem.*mozart'),
 ('mozart-queen-of-night', 'Queen of the Night Aria (Der Hölle Rache)', r'queen of the night|der h[oö]lle rache'),
 ('mozart-papageno', 'Papageno’s Song from The Magic Flute', r'papageno|vogelf[aä]nger'),
 ('mozart-magic-flute-overture', 'Overture to The Magic Flute', r'magic flute|zauberfl'),
 ('mozart-figaro-overture', 'Overture to The Marriage of Figaro', r'figaro'),
 ('mozart-don-giovanni', 'Là ci darem la mano (Don Giovanni)', r'ci darem|don giovanni'),
 ('mozart-piano-concerto-21', 'Piano Concerto No. 21 · Andante (“Elvira Madigan”)', cat('k',467) + r'|concerto (no\.? ?)?21|elvira madigan'),
 ('mozart-piano-concerto-23', 'Piano Concerto No. 23 · Adagio', cat('k',488)),
 ('mozart-minuet-k2', 'Minuet in F, K. 2', cat('k',2) + r'\b'),
 ('mozart-minuet-k1', 'Minuet in G, K. 1', cat('k','1e?') + r'|minuet in g.*k\.? ?1\b'),
 ('mozart-allegro-k3', 'Allegro in B-flat, K. 3', cat('k',3)),
 ('mozart-minuet-k5', 'Minuet in F, K. 5', cat('k',5)),
 ('mozart-ave-verum', 'Ave verum corpus, K. 618', r'ave verum|' + cat('k',618)),
 ('mozart-adagio-k540', 'Adagio in B minor, K. 540', cat('k',540)),
 ('mozart-rondo-k485', 'Rondo in D, K. 485', cat('k',485)),
 ('mozart-rondo-k511', 'Rondo in A minor, K. 511', cat('k',511)),
 ('mozart-lullaby', 'Wiegenlied (Mozart’s Lullaby)', r'wiegenlied.*mozart|mozart.*lullaby'),
 ('mozart-turkish-march-easy', 'Turkish March · easy version', r'(turkish march|alla turca).*(easy|simplified|beginner)'),
 ('mozart-symphony-41', 'Symphony No. 41 “Jupiter” · first movement', r'jupiter|' + cat('k',551)),
 ('mozart-horn-concerto-4', 'Horn Concerto No. 4 · Rondo', cat('k',495) + r'|horn concerto'),
 ('mozart-clarinet-concerto', 'Clarinet Concerto · Adagio', cat('k',622) + r'|clarinet concerto'),
])
add('beethoven', 'Classical', [
 ('beethoven-moonlight-3', 'Moonlight Sonata · third movement', r'(moonlight|' + op(27, 2) + r').*(3rd|third|iii\b|presto)'),
 ('beethoven-moonlight-2', 'Moonlight Sonata · second movement', r'(moonlight|' + op(27, 2) + r').*(2nd|second|ii\b|allegretto)'),
 ('beethoven-pathetique-1', 'Pathétique Sonata · first movement', r'(path[eé]tique|' + op(13) + r').*(1st|first|\bi\b|grave|allegro di molto)'),
 ('beethoven-pathetique-3', 'Pathétique Sonata · third movement', r'(path[eé]tique|' + op(13) + r').*(3rd|third|iii\b|rondo)'),
 ('beethoven-tempest-3', 'Tempest Sonata · third movement', r'(tempest|' + op(31, 2) + r').*(3rd|third|iii|allegretto)'),
 ('beethoven-appassionata', 'Appassionata Sonata · first movement', r'appassionata|' + op(57)),
 ('beethoven-waldstein', 'Waldstein Sonata · first movement', r'waldstein|' + op(53)),
 ('beethoven-sonata-49-2', 'Sonata in G, Op. 49 No. 2 · first movement', op(49, 2)),
 ('beethoven-sonata-49-1', 'Sonata in G minor, Op. 49 No. 1', op(49, 1)),
 ('beethoven-sonata-79', 'Sonata in G, Op. 79', op(79)),
 ('beethoven-sonata-10-1', 'Sonata in C minor, Op. 10 No. 1', op(10, 1)),
 ('beethoven-sonata-2-1', 'Sonata in F minor, Op. 2 No. 1 · first movement', op(2, 1)),
 ('beethoven-sonatina-g', 'Sonatina in G major, Anh. 5', r'sonatina in g|anh\.? ?5'),
 ('beethoven-sonatina-f', 'Sonatina in F major, Anh. 5 No. 2', r'sonatina in f.*beethoven'),
 ('beethoven-bagatelle-33', 'Bagatelle, Op. 33', op(33)),
 ('beethoven-bagatelle-119', 'Bagatelle, Op. 119', op(119)),
 ('beethoven-bagatelle-126', 'Bagatelle, Op. 126', op(126)),
 ('beethoven-rage-penny', 'Rage over a Lost Penny, Op. 129', r'lost penny|' + op(129)),
 ('beethoven-ecossaise', 'Écossaise in G, WoO 23', r'[eé]cossaise'),
 ('beethoven-symphony-5', 'Symphony No. 5 · first movement', r'symphony (no\.? ?)?5|fifth symphony|' + op(67)),
 ('beethoven-symphony-7', 'Symphony No. 7 · Allegretto', r'symphony (no\.? ?)?7|' + op(92)),
 ('beethoven-symphony-9', 'Symphony No. 9 · Ode to Joy (complete theme)', r'symphony (no\.? ?)?9\b|' + op(125)),
 ('beethoven-symphony-6', 'Symphony No. 6 “Pastoral” · first movement', r'pastoral symphony|symphony (no\.? ?)?6|' + op(68)),
 ('beethoven-emperor-concerto', 'Piano Concerto No. 5 “Emperor” · Adagio', r'emperor concerto|concerto (no\.? ?)?5|' + op(73)),
 ('beethoven-turkish-march', 'Turkish March (from The Ruins of Athens)', r'turkish march.*beethoven|beethoven.*turkish march|ruins of athens'),
 ('beethoven-minuet-g', 'Minuet in G, WoO 10 No. 2', r'minuet in g.*beethoven|woo\.? ?10'),
 ('beethoven-variations-nel-cor', 'Six Variations on “Nel cor più non mi sento”', r'nel cor'),
 ('beethoven-32-variations', '32 Variations in C minor, WoO 80', r'32 variations|woo\.? ?80'),
 ('beethoven-sonata-14-2', 'Sonata in G, Op. 14 No. 2', op(14, 2)),
 ('beethoven-les-adieux', 'Les Adieux Sonata, Op. 81a', r'les adieux|' + op('81a')),
 ('beethoven-sonata-109', 'Sonata in E, Op. 109', op(109)),
 ('beethoven-sonata-110', 'Sonata in A-flat, Op. 110', op(110)),
 ('beethoven-spring-sonata', 'Spring Sonata · first movement', r'spring sonata|' + op(24)),
 ('beethoven-romance-f', 'Romance in F, Op. 50', op(50) + r'|romance in f'),
 ('beethoven-contredanse', 'Contredanse in E-flat, WoO 14', r'contredanse|contradance'),
 ('beethoven-german-dance', 'German Dance', r'german dance.*beethoven|beethoven.*german dance'),
])
add('schubert', 'Romantic', [
 ('schubert-serenade', 'Serenade (Ständchen), D. 957', r'st[aä]ndchen|serenade.*schubert|schubert.*serenade|d\.? ?957'),
 ('schubert-ave-maria', 'Ave Maria, D. 839', r'ave maria'),
 ('schubert-moment-musical-3', 'Moment Musical No. 3 in F minor', r'moment(s)? musica[lu]x?.*(3|iii|f minor)'),
 ('schubert-impromptu-90-2', 'Impromptu in E-flat, D. 899 No. 2', r'd\.? ?899\D*2\b|' + op(90, 2)),
 ('schubert-impromptu-90-4', 'Impromptu in A-flat, D. 899 No. 4', r'd\.? ?899\D*4\b|' + op(90, 4)),
 ('schubert-impromptu-90-1', 'Impromptu in C minor, D. 899 No. 1', r'd\.? ?899\D*1\b|' + op(90, 1)),
 ('schubert-impromptu-142-2', 'Impromptu in A-flat, D. 935 No. 2', r'd\.? ?935\D*2\b|' + op(142, 2)),
 ('schubert-impromptu-142-3', 'Impromptu in B-flat, D. 935 No. 3', r'd\.? ?935\D*3\b|' + op(142, 3)),
 ('schubert-erlkonig', 'Erlkönig, D. 328', r'erlk[oö]e?nig|d\.? ?328'),
 ('schubert-unfinished', 'Unfinished Symphony · first movement', r'unfinished|symphony (no\.? ?)?8'),
 ('schubert-marche-militaire', 'Marche militaire No. 1', r'marche militaire|military march'),
 ('schubert-trout', 'The Trout (Die Forelle)', r'forelle|trout'),
 ('schubert-standchen-waltz', 'Waltz in A-flat, D. 365 No. 2', r'd\.? ?365'),
 ('schubert-sonata-d664', 'Sonata in A, D. 664 · first movement', r'd\.? ?664'),
 ('schubert-sonata-d960', 'Sonata in B-flat, D. 960 · first movement', r'd\.? ?960'),
 ('schubert-rosamunde', 'Rosamunde · Entr’acte', r'rosamunde'),
 ('schubert-heidenroslein', 'Heidenröslein', r'heidenr'),
 ('schubert-wanderer', 'Der Lindenbaum', r'lindenbaum'),
 ('schubert-ecossaise', 'Écossaises, D. 781', r'[eé]cossaise'),
])
add('chopin', 'Romantic', [
 ('chopin-nocturne-20', 'Nocturne in C minor, Op. 48 No. 1', '$^'),
 ('chopin-nocturne-op27-2', 'Nocturne in D-flat, Op. 27 No. 2', op(27, 2)),
 ('chopin-nocturne-op27-1', 'Nocturne in C-sharp minor, Op. 27 No. 1', op(27, 1)),
 ('chopin-nocturne-op15-2', 'Nocturne in F-sharp, Op. 15 No. 2', op(15, 2)),
 ('chopin-nocturne-op15-1', 'Nocturne in F, Op. 15 No. 1', op(15, 1)),
 ('chopin-nocturne-op32-1', 'Nocturne in B, Op. 32 No. 1', op(32, 1)),
 ('chopin-nocturne-op37-1', 'Nocturne in G minor, Op. 37 No. 1', op(37, 1)),
 ('chopin-nocturne-op55-1', 'Nocturne in F minor, Op. 55 No. 1', op(55, 1)),
 ('chopin-nocturne-op62-1', 'Nocturne in B, Op. 62 No. 1', op(62, 1)),
 ('chopin-nocturne-op72-1', 'Nocturne in E minor, Op. 72 No. 1', op(72, 1)),
 ('chopin-nocturne-c-minor-posth', 'Nocturne in C minor, B. 108 (posth.)', r'nocturne in c minor.*(posth|b\.? ?108|kk)'),
 ('chopin-nocturne-op9-3', 'Nocturne in B, Op. 9 No. 3', op(9, 3)),
 ('chopin-waltz-64-3', 'Waltz in A-flat, Op. 64 No. 3', op(64, 3)),
 ('chopin-waltz-69-1', 'Waltz in A-flat, Op. 69 No. 1 “Farewell”', op(69, 1) + r'|farewell waltz|l.adieu'),
 ('chopin-waltz-69-2', 'Waltz in B minor, Op. 69 No. 2', op(69, 2)),
 ('chopin-waltz-70-1', 'Waltz in G-flat, Op. 70 No. 1', op(70, 1)),
 ('chopin-waltz-70-2', 'Waltz in F minor, Op. 70 No. 2', op(70, 2)),
 ('chopin-waltz-34-1', 'Waltz in A-flat, Op. 34 No. 1', op(34, 1)),
 ('chopin-waltz-34-2', 'Waltz in A minor, Op. 34 No. 2', op(34, 2)),
 ('chopin-waltz-18', 'Grande valse brillante, Op. 18', op(18) + r'|grande valse brillante'),
 ('chopin-waltz-42', 'Waltz in A-flat, Op. 42', op(42)),
 ('chopin-waltz-e-minor', 'Waltz in E minor, B. 56 (posth.)', r'waltz in e minor|b\.? ?56'),
 ('chopin-waltz-a-minor-posth', 'Waltz in A minor, B. 150 (posth.)', r'waltz in a minor|b\.? ?150'),
 ('chopin-prelude-7', 'Prelude in A, Op. 28 No. 7', op(28, 7)),
 ('chopin-prelude-20', 'Prelude in C minor, Op. 28 No. 20', op(28, 20)),
 ('chopin-prelude-6', 'Prelude in B minor, Op. 28 No. 6', op(28, 6)),
 ('chopin-prelude-1', 'Prelude in C, Op. 28 No. 1', op(28, 1)),
 ('chopin-prelude-24', 'Prelude in D minor, Op. 28 No. 24', op(28, 24)),
 ('chopin-prelude-16', 'Prelude in B-flat minor, Op. 28 No. 16', op(28, 16)),
 ('chopin-prelude-17', 'Prelude in A-flat, Op. 28 No. 17', op(28, 17)),
 ('chopin-prelude-9', 'Prelude in E, Op. 28 No. 9', op(28, 9)),
 ('chopin-prelude-13', 'Prelude in F-sharp, Op. 28 No. 13', op(28, 13)),
 ('chopin-prelude-21', 'Prelude in B-flat, Op. 28 No. 21', op(28, 21)),
 ('chopin-prelude-2', 'Prelude in A minor, Op. 28 No. 2', op(28, 2)),
 ('chopin-prelude-3', 'Prelude in G, Op. 28 No. 3', op(28, 3)),
 ('chopin-prelude-8', 'Prelude in F-sharp minor, Op. 28 No. 8', op(28, 8)),
 ('chopin-prelude-10', 'Prelude in C-sharp minor, Op. 28 No. 10', op(28, 10)),
 ('chopin-prelude-11', 'Prelude in B, Op. 28 No. 11', op(28, 11)),
 ('chopin-prelude-12', 'Prelude in G-sharp minor, Op. 28 No. 12', op(28, 12)),
 ('chopin-prelude-14', 'Prelude in E-flat minor, Op. 28 No. 14', op(28, 14)),
 ('chopin-prelude-18', 'Prelude in F minor, Op. 28 No. 18', op(28, 18)),
 ('chopin-prelude-19', 'Prelude in E-flat, Op. 28 No. 19', op(28, 19)),
 ('chopin-prelude-22', 'Prelude in G minor, Op. 28 No. 22', op(28, 22)),
 ('chopin-prelude-23', 'Prelude in F, Op. 28 No. 23', op(28, 23)),
 ('chopin-prelude-5', 'Prelude in D, Op. 28 No. 5', op(28, 5)),
 ('chopin-etude-10-1', 'Étude in C, Op. 10 No. 1', op(10, 1)),
 ('chopin-etude-10-5', 'Étude in G-flat, Op. 10 No. 5 “Black Keys”', op(10, 5) + r'|black key'),
 ('chopin-etude-10-2', 'Étude in A minor, Op. 10 No. 2', op(10, 2)),
 ('chopin-etude-10-6', 'Étude in E-flat minor, Op. 10 No. 6', op(10, 6)),
 ('chopin-etude-10-8', 'Étude in F, Op. 10 No. 8', op(10, 8)),
 ('chopin-etude-25-1', 'Étude in A-flat, Op. 25 No. 1 “Aeolian Harp”', op(25, 1) + r'|aeolian harp'),
 ('chopin-etude-25-9', 'Étude in G-flat, Op. 25 No. 9 “Butterfly”', op(25, 9) + r'|butterfl'),
 ('chopin-etude-25-12', 'Étude in C minor, Op. 25 No. 12 “Ocean”', op(25, 12) + r'|ocean'),
 ('chopin-etude-25-5', 'Étude in E minor, Op. 25 No. 5', op(25, 5)),
 ('chopin-etude-25-7', 'Étude in C-sharp minor, Op. 25 No. 7', op(25, 7)),
 ('chopin-etude-25-2', 'Étude in F minor, Op. 25 No. 2', op(25, 2)),
 ('chopin-etude-25-6', 'Étude in G-sharp minor, Op. 25 No. 6', op(25, 6)),
 ('chopin-ballade-2', 'Ballade No. 2 in F, Op. 38', op(38) + r'|ballade (no\.? ?)?2'),
 ('chopin-ballade-3', 'Ballade No. 3 in A-flat, Op. 47', op(47) + r'|ballade (no\.? ?)?3'),
 ('chopin-ballade-4', 'Ballade No. 4 in F minor, Op. 52', op(52) + r'|ballade (no\.? ?)?4'),
 ('chopin-scherzo-2', 'Scherzo No. 2 in B-flat minor, Op. 31', op(31) + r'|scherzo (no\.? ?)?2'),
 ('chopin-scherzo-1', 'Scherzo No. 1 in B minor, Op. 20', op(20) + r'|scherzo (no\.? ?)?1\b'),
 ('chopin-scherzo-3', 'Scherzo No. 3 in C-sharp minor, Op. 39', op(39)),
 ('chopin-impromptu-1', 'Impromptu No. 1 in A-flat, Op. 29', op(29)),
 ('chopin-polonaise-40-1', 'Polonaise in A, Op. 40 No. 1 “Military”', op(40, 1) + r'|military polonaise'),
 ('chopin-polonaise-26-1', 'Polonaise in C-sharp minor, Op. 26 No. 1', op(26, 1)),
 ('chopin-polonaise-g-minor', 'Polonaise in G minor, B. 1', r'polonaise in g minor.*chopin|chopin.*polonaise in g minor'),
 ('chopin-polonaise-fantaisie', 'Polonaise-Fantaisie, Op. 61', op(61)),
 ('chopin-andante-spianato', 'Andante spianato and Grande Polonaise, Op. 22', op(22) + r'|spianato'),
 ('chopin-mazurka-7-1', 'Mazurka in B-flat, Op. 7 No. 1', op(7, 1)),
 ('chopin-mazurka-17-4', 'Mazurka in A minor, Op. 17 No. 4', op(17, 4)),
 ('chopin-mazurka-68-3', 'Mazurka in F, Op. 68 No. 3', op(68, 3)),
 ('chopin-mazurka-67-4', 'Mazurka in A minor, Op. 67 No. 4', op(67, 4)),
 ('chopin-mazurka-68-2', 'Mazurka in A minor, Op. 68 No. 2', op(68, 2)),
 ('chopin-mazurka-33-4', 'Mazurka in B minor, Op. 33 No. 4', op(33, 4)),
 ('chopin-mazurka-6-1', 'Mazurka in F-sharp minor, Op. 6 No. 1', op(6, 1)),
 ('chopin-mazurka-24-4', 'Mazurka in B-flat minor, Op. 24 No. 4', op(24, 4)),
 ('chopin-berceuse', 'Berceuse, Op. 57', op(57) + r'|berceuse'),
 ('chopin-barcarolle', 'Barcarolle, Op. 60', op(60) + r'|barcarolle'),
 ('chopin-funeral-march', 'Funeral March (Sonata No. 2, third movement)', op(35) + r'|funeral march|marche fun'),
 ('chopin-sonata-3-finale', 'Sonata No. 3 · finale', op(58)),
 ('chopin-fantaisie-49', 'Fantaisie in F minor, Op. 49', op(49)),
 ('chopin-contredanse', 'Contredanse in G-flat', r'contredanse'),
 ('chopin-largo', 'Largo in E-flat, B. 109', r'largo'),
 ('chopin-cantabile', 'Cantabile in B-flat, B. 84', r'cantabile'),
 ('chopin-lento', 'Lento con gran espressione (Nocturne in C-sharp minor)', '$^'),
 ('chopin-concerto-1-romanze', 'Piano Concerto No. 1 · Romanze', op(11)),
 ('chopin-concerto-2-larghetto', 'Piano Concerto No. 2 · Larghetto', op(21)),
])
add('liszt', 'Romantic', [
 ('liszt-hungarian-2', 'Hungarian Rhapsody No. 2', r'hungarian rhapsody (no\.? ?)?2|rhapsodie hongroise (no\.? ?)?2'),
 ('liszt-liebestraum-1', 'Liebestraum No. 1', r'liebestr[aä]e?um (no\.? ?)?1'),
 ('liszt-un-sospiro', 'Un sospiro', r'sospiro'),
 ('liszt-consolation-1', 'Consolation No. 1', r'consolation (no\.? ?)?1\b'),
 ('liszt-consolation-2', 'Consolation No. 2', r'consolation (no\.? ?)?2'),
 ('liszt-transcendental-4', 'Mazeppa (Transcendental Étude No. 4)', r'mazeppa'),
 ('liszt-feux-follets', 'Feux follets', r'feux follets'),
 ('liszt-chasse-neige', 'Chasse-neige', r'chasse.neige'),
 ('liszt-paysage', 'Paysage (Transcendental Étude No. 3)', r'paysage'),
 ('liszt-gnomenreigen', 'Gnomenreigen', r'gnomenreigen'),
 ('liszt-waldesrauschen', 'Waldesrauschen', r'waldesrauschen'),
 ('liszt-mephisto', 'Mephisto Waltz No. 1', r'mephisto'),
 ('liszt-petrarch-104', 'Petrarch Sonnet 104', r'sonnet|sonetto'),
 ('liszt-ave-maria', 'Ave Maria (after Schubert)', r'ave maria'),
 ('liszt-standchen', 'Ständchen (after Schubert)', r'st[aä]e?ndchen|serenade'),
 ('liszt-hungarian-6', 'Hungarian Rhapsody No. 6', r'hungarian rhapsody (no\.? ?)?6'),
 ('liszt-grand-galop', 'Grand galop chromatique', r'galop'),
 ('liszt-etude-paganini-6', 'Paganini Étude No. 6', r'paganini.*(6|vi)\b'),
 ('liszt-nuages-gris', 'Nuages gris', r'nuages gris'),
 ('liszt-funerailles', 'Funérailles', r'fun[eé]railles'),
])
add('schumann', 'Romantic', [
 ('schumann-soldiers-march', 'Soldiers’ March, Op. 68 No. 2', op(68, 2) + r'|soldier'),
 ('schumann-first-loss', 'First Loss, Op. 68 No. 16', op(68, 16) + r'|first loss|erster verlust'),
 ('schumann-humming-song', 'Humming Song, Op. 68 No. 3', op(68, 3)),
 ('schumann-sicilienne', 'Sicilienne, Op. 68 No. 11', op(68, 11)),
 ('schumann-knecht-ruprecht', 'Knecht Ruprecht, Op. 68 No. 12', op(68, 12)),
 ('schumann-little-piece', 'A Little Piece, Op. 68 No. 5', op(68, 5)),
 ('schumann-hunting-song', 'Hunting Song, Op. 68 No. 7', op(68, 7)),
 ('schumann-reaper', 'Reaper’s Song, Op. 68 No. 18', op(68, 18)),
 ('schumann-lively-farmer', 'Little Romance, Op. 68 No. 19', op(68, 19)),
 ('schumann-merry-farmer-chorale', 'Chorale, Op. 68 No. 4', op(68, 4)),
 ('schumann-strange-lands', 'Of Foreign Lands and Peoples, Op. 15 No. 1', op(15, 1) + r'|foreign lands|fremden l'),
 ('schumann-curious-story', 'A Curious Story, Op. 15 No. 2', op(15, 2)),
 ('schumann-blindmans-buff', 'Blind Man’s Buff, Op. 15 No. 3', op(15, 3)),
 ('schumann-pleading-child', 'Pleading Child, Op. 15 No. 4', op(15, 4)),
 ('schumann-happy-enough', 'Happy Enough, Op. 15 No. 5', op(15, 5)),
 ('schumann-important-event', 'An Important Event, Op. 15 No. 6', op(15, 6)),
 ('schumann-child-falling-asleep', 'Child Falling Asleep, Op. 15 No. 12', op(15, 12)),
 ('schumann-poet-speaks', 'The Poet Speaks, Op. 15 No. 13', op(15, 13)),
 ('schumann-arabeske', 'Arabeske, Op. 18', op(18) + r'|arabeske'),
 ('schumann-widmung', 'Widmung (Dedication)', r'widmung|dedication'),
 ('schumann-aufschwung', 'Aufschwung, Op. 12 No. 2', op(12, 2) + r'|aufschwung'),
 ('schumann-des-abends', 'Des Abends, Op. 12 No. 1', op(12, 1)),
 ('schumann-warum', 'Warum?, Op. 12 No. 3', op(12, 3)),
 ('schumann-romance-28-2', 'Romance in F-sharp, Op. 28 No. 2', op(28, 2)),
 ('schumann-scenes-forest', 'The Prophet Bird, Op. 82 No. 7', op(82, 7) + r'|prophet bird'),
 ('schumann-kinderszenen-1', 'Catch Me (Hasche-Mann), Op. 15 No. 3', '$^'),
 ('schumann-album-41', 'Northern Song, Op. 68 No. 41', op(68, 41)),
 ('schumann-wintertime', 'Wintertime I, Op. 68 No. 38', op(68, 38)),
 ('schumann-santa-claus', 'Little Study, Op. 68 No. 14', op(68, 14)),
 ('schumann-sheherazade', 'Echoes from the Theatre, Op. 68 No. 25', op(68, 25)),
])
add('mendelssohn', 'Romantic', [
 ('mendelssohn-spring-song', 'Spring Song, Op. 62 No. 6', op(62, 6) + r'|spring song|fr[uü]hlingslied'),
 ('mendelssohn-venetian-boat-1', 'Venetian Boat Song, Op. 19 No. 6', op(19, 6) + r'|venetian'),
 ('mendelssohn-sweet-remembrance', 'Sweet Remembrance, Op. 19 No. 1', op(19, 1)),
 ('mendelssohn-consolation', 'Consolation, Op. 30 No. 3', op(30, 3)),
 ('mendelssohn-spinning-song', 'Spinning Song, Op. 67 No. 4', op(67, 4) + r'|spinnerlied'),
 ('mendelssohn-duetto', 'Duetto, Op. 38 No. 6', op(38, 6)),
 ('mendelssohn-op102-3', 'Song without Words, Op. 102 No. 3', op(102, 3)),
 ('mendelssohn-op30-6', 'Venetian Boat Song, Op. 30 No. 6', op(30, 6)),
 ('mendelssohn-op53-2', 'Song without Words, Op. 53 No. 2', op(53, 2)),
 ('mendelssohn-wedding-march', 'Wedding March from A Midsummer Night’s Dream', r'wedding march|midsummer'),
 ('mendelssohn-rondo-capriccioso', 'Rondo capriccioso, Op. 14', op(14) + r'|rondo capriccioso'),
 ('mendelssohn-violin-concerto', 'Violin Concerto in E minor · first movement', r'violin concerto|' + op(64)),
 ('mendelssohn-variations-serieuses', 'Variations sérieuses, Op. 54', op(54) + r'|s[eé]rieuses'),
 ('mendelssohn-hark-herald', 'Hark! The Herald Angels Sing', '$^'),
 ('mendelssohn-op19-2', 'Regrets, Op. 19 No. 2', op(19, 2)),
 ('mendelssohn-op85-4', 'Song without Words, Op. 85 No. 4', op(85, 4)),
 ('mendelssohn-op19-5', 'Restlessness, Op. 19 No. 5', op(19, 5)),
 ('mendelssohn-op62-1', 'May Breezes, Op. 62 No. 1', op(62, 1)),
 ('mendelssohn-op62-3', 'Funeral March, Op. 62 No. 3', op(62, 3)),
 ('mendelssohn-op19-3', 'Hunting Song, Op. 19 No. 3', op(19, 3)),
])
add('brahms', 'Romantic', [
 ('brahms-lullaby', 'Lullaby (Wiegenlied), Op. 49 No. 4', r'lullaby|wiegenlied|' + op(49, 4)),
 ('brahms-hungarian-5', 'Hungarian Dance No. 5', r'hungarian dance (no\.? ?)?5'),
 ('brahms-hungarian-1', 'Hungarian Dance No. 1', r'hungarian dance (no\.? ?)?1\b'),
 ('brahms-intermezzo-118-2', 'Intermezzo in A, Op. 118 No. 2', op(118, 2)),
 ('brahms-intermezzo-117-1', 'Intermezzo in E-flat, Op. 117 No. 1', op(117, 1)),
 ('brahms-intermezzo-117-2', 'Intermezzo in B-flat minor, Op. 117 No. 2', op(117, 2)),
 ('brahms-intermezzo-116-4', 'Intermezzo in E, Op. 116 No. 4', op(116, 4)),
 ('brahms-rhapsody-79-2', 'Rhapsody in G minor, Op. 79 No. 2', op(79, 2)),
 ('brahms-rhapsody-79-1', 'Rhapsody in B minor, Op. 79 No. 1', op(79, 1)),
 ('brahms-ballade-10-1', 'Ballade in D minor “Edward”, Op. 10 No. 1', op(10, 1)),
 ('brahms-romance-118-5', 'Romance in F, Op. 118 No. 5', op(118, 5)),
 ('brahms-ballade-118-3', 'Ballade in G minor, Op. 118 No. 3', op(118, 3)),
 ('brahms-capriccio-76-2', 'Capriccio in B minor, Op. 76 No. 2', op(76, 2)),
 ('brahms-intermezzo-119-1', 'Intermezzo in B minor, Op. 119 No. 1', op(119, 1)),
 ('brahms-symphony-3', 'Symphony No. 3 · third movement', r'symphony (no\.? ?)?3|' + op(90)),
 ('brahms-waltz-39-1', 'Waltz in B, Op. 39 No. 1', op(39, 1)),
 ('brahms-waltz-39-3', 'Waltz in G-sharp minor, Op. 39 No. 3', op(39, 3)),
 ('brahms-academic', 'Academic Festival Overture', r'academic festival'),
])
add('tchaikovsky', 'Opera & ballet', [
 ('tchaikovsky-swan-lake', 'Swan Lake · Scene (Act II theme)', r'swan lake.*(scene|theme|act ii|act 2)|^swan lake$|swan lake'),
 ('tchaikovsky-dance-little-swans', 'Dance of the Little Swans', r'little swans|cygnets'),
 ('tchaikovsky-sugar-plum', 'Dance of the Sugar Plum Fairy', r'sugar ?plum'),
 ('tchaikovsky-waltz-flowers', 'Waltz of the Flowers', r'waltz of the flowers|flower waltz|valse des fleurs'),
 ('tchaikovsky-nutcracker-march', 'March from The Nutcracker', r'nutcracker.*march|march.*nutcracker'),
 ('tchaikovsky-russian-dance', 'Russian Dance (Trepak)', r'trepak|russian dance'),
 ('tchaikovsky-nutcracker-overture', 'Miniature Overture from The Nutcracker', r'miniature overture'),
 ('tchaikovsky-arabian-dance', 'Arabian Dance (Coffee)', r'arabian dance'),
 ('tchaikovsky-chinese-dance', 'Chinese Dance (Tea)', r'chinese dance'),
 ('tchaikovsky-reed-flutes', 'Dance of the Reed Flutes', r'reed.?pipes|reed flutes|mirlitons'),
 ('tchaikovsky-sleeping-beauty-waltz', 'Waltz from Sleeping Beauty', r'sleeping beauty'),
 ('tchaikovsky-swan-lake-waltz', 'Waltz from Swan Lake', r'swan lake.*waltz'),
 ('tchaikovsky-june', 'June · Barcarolle (The Seasons)', r'june|barcarolle'),
 ('tchaikovsky-october', 'October · Autumn Song (The Seasons)', r'october|autumn song'),
 ('tchaikovsky-december', 'December · Christmas (The Seasons)', r'december'),
 ('tchaikovsky-january', 'January · At the Fireside (The Seasons)', r'january|fireside'),
 ('tchaikovsky-november', 'November · Troika (The Seasons)', r'november|troika'),
 ('tchaikovsky-sweet-dream', 'Sweet Dreams, Op. 39 No. 21', r'sweet dream|' + op(39, 21)),
 ('tchaikovsky-old-french-song', 'Old French Song, Op. 39 No. 16', r'old french song|' + op(39, 16)),
 ('tchaikovsky-morning-prayer', 'Morning Prayer, Op. 39 No. 1', r'morning prayer|' + op(39, 1)),
 ('tchaikovsky-sick-doll', 'The Sick Doll, Op. 39 No. 7', r'sick doll|doll.?s (illness|funeral)'),
 ('tchaikovsky-italian-song', 'Italian Song, Op. 39 No. 15', r'italian song'),
 ('tchaikovsky-mazurka-39', 'Mazurka, Op. 39 No. 10', op(39, 10)),
 ('tchaikovsky-piano-concerto-1', 'Piano Concerto No. 1 · opening', r'piano concerto (no\.? ?)?1|' + op(23)),
 ('tchaikovsky-1812', '1812 Overture', r'1812'),
 ('tchaikovsky-chanson-triste', 'Chanson triste, Op. 40 No. 2', r'chanson triste'),
 ('tchaikovsky-symphony-6', 'Symphony No. 6 “Pathétique” · first movement theme', r'symphony (no\.? ?)?6|path[eé]tique symphony'),
 ('tchaikovsky-symphony-5', 'Symphony No. 5 · Andante cantabile', r'symphony (no\.? ?)?5'),
 ('tchaikovsky-romeo-juliet', 'Romeo and Juliet · love theme', r'romeo'),
 ('tchaikovsky-valse-sentimentale', 'Valse sentimentale, Op. 51 No. 6', r'valse sentimentale'),
 ('tchaikovsky-nocturne-19-4', 'Nocturne, Op. 19 No. 4', op(19, 4)),
 ('tchaikovsky-andante-cantabile', 'Andante cantabile (String Quartet No. 1)', r'andante cantabile'),
])
add('debussy', 'Impressionist & modern', [
 ('debussy-reverie', 'Rêverie', r'r[eê]verie'),
 ('debussy-arabesque-2', 'Arabesque No. 2', r'arabesque (no\.? ?)?2'),
 ('debussy-girl-flaxen-hair', 'The Girl with the Flaxen Hair', r'flaxen|fille aux cheveux'),
 ('debussy-golliwog', 'Golliwogg’s Cakewalk', r'golliwog|cakewalk'),
 ('debussy-doctor-gradus', 'Doctor Gradus ad Parnassum', r'gradus'),
 ('debussy-snow-dancing', 'The Snow Is Dancing', r'snow is dancing|neige danse'),
 ('debussy-jimbo', 'Jimbo’s Lullaby', r'jimbo'),
 ('debussy-little-shepherd', 'The Little Shepherd', r'little shepherd|petit berger'),
 ('debussy-passepied', 'Passepied (Suite bergamasque)', r'passepied'),
 ('debussy-prelude-bergamasque', 'Prélude (Suite bergamasque)', r'bergamasque.*(pr[eé]lude)|pr[eé]lude.*bergamasque'),
 ('debussy-menuet-bergamasque', 'Menuet (Suite bergamasque)', r'bergamasque.*menuet|menuet.*bergamasque'),
 ('debussy-valse-romantique', 'Valse romantique', r'valse romantique'),
 ('debussy-plus-que-lente', 'La plus que lente', r'plus que lente'),
 ('debussy-sunken-cathedral', 'The Sunken Cathedral', r'cath[eé]drale engloutie|sunken cathedral'),
 ('debussy-minstrels', 'Minstrels', r'minstrels'),
 ('debussy-pagodes', 'Pagodes', r'pagodes'),
 ('debussy-jardins-pluie', 'Jardins sous la pluie', r'jardins sous la pluie|gardens in the rain'),
 ('debussy-reflets', 'Reflets dans l’eau', r'reflets dans'),
 ('debussy-nocturne', 'Nocturne (1892)', r'^nocturne$|nocturne.*debussy'),
 ('debussy-mazurka', 'Mazurka', r'mazurka'),
 ('debussy-ballade', 'Ballade', r'ballade'),
 ('debussy-danse', 'Danse (Tarentelle styrienne)', r'tarentelle|^danse$'),
 ('debussy-ce-qua-vu', 'Des pas sur la neige', r'pas sur la neige|footprints in the snow'),
 ('debussy-hommage-rameau', 'Hommage à Rameau', r'hommage'),
 ('debussy-faune', 'Prelude to the Afternoon of a Faun', r'faun'),
 ('debussy-beau-soir', 'Beau soir', r'beau soir'),
 ('debussy-la-mer', 'La Mer · opening', r'la mer\b'),
])
add('satie', 'Impressionist & modern', [
 ('satie-gymnopedie-2', 'Gymnopédie No. 2', r'gymnop[eé]die (no\.? ?)?2'),
 ('satie-gymnopedie-3', 'Gymnopédie No. 3', r'gymnop[eé]die (no\.? ?)?3'),
 ('satie-gnossienne-2', 'Gnossienne No. 2', r'gnossienne (no\.? ?)?2'),
 ('satie-gnossienne-3', 'Gnossienne No. 3', r'gnossienne (no\.? ?)?3'),
 ('satie-gnossienne-4', 'Gnossienne No. 4', r'gnossienne (no\.? ?)?4'),
 ('satie-gnossienne-5', 'Gnossienne No. 5', r'gnossienne (no\.? ?)?5'),
 ('satie-gnossienne-6', 'Gnossienne No. 6', r'gnossienne (no\.? ?)?6'),
 ('satie-je-te-veux', 'Je te veux', r'je te veux'),
 ('satie-vexations', 'Vexations', r'vexations'),
 ('satie-ogives', 'Ogive No. 1', r'ogive'),
 ('satie-sarabande', 'Sarabande No. 1', r'sarabande'),
 ('satie-picadilly', 'The Picadilly', r'picadilly|piccadilly'),
 ('satie-pieces-froides', 'Pièces froides · Airs à faire fuir', r'pi[eè]ces froides|airs [aà] faire'),
 ('satie-reverie', 'Rêverie du pauvre', r'r[eê]verie'),
 ('satie-prelude-eginhard', 'Prélude d’Eginhard', r'eginhard'),
])
add('ravel', 'Impressionist & modern', [
 ('ravel-pavane', 'Pavane for a Dead Princess', r'pavane'),
 ('ravel-bolero', 'Boléro', r'bol[eé]ro'),
 ('ravel-sonatine', 'Sonatine · first movement', r'sonatine'),
 ('ravel-menuet-haydn', 'Menuet sur le nom d’Haydn', r'haydn'),
 ('ravel-menuet-antique', 'Menuet antique', r'menuet antique'),
 ('ravel-prelude', 'Prélude (1913)', r'^pr[eé]lude'),
 ('ravel-jeux-deau', 'Jeux d’eau', r'jeux d.eau'),
 ('ravel-ondine', 'Ondine', r'ondine'),
 ('ravel-a-la-maniere', 'À la manière de Borodine', r'mani[eè]re'),
 ('ravel-mother-goose', 'Pavane of Sleeping Beauty (Mother Goose)', r'mother goose|ma m[eè]re'),
])
add('rachmaninoff', 'Romantic', [
 ('rachmaninoff-vocalise', 'Vocalise, Op. 34 No. 14', r'vocalise'),
 ('rachmaninoff-concerto-2', 'Piano Concerto No. 2 · opening', r'concerto (no\.? ?)?2|' + op(18)),
 ('rachmaninoff-prelude-g-minor', 'Prelude in G minor, Op. 23 No. 5', op(23, 5)),
 ('rachmaninoff-prelude-b-minor', 'Prelude in B minor, Op. 32 No. 10', op(32, 10)),
 ('rachmaninoff-prelude-g-sharp', 'Prelude in G-sharp minor, Op. 32 No. 12', op(32, 12)),
 ('rachmaninoff-prelude-d', 'Prelude in D, Op. 23 No. 4', op(23, 4)),
 ('rachmaninoff-elegie', 'Élégie, Op. 3 No. 1', op(3, 1) + r'|[eé]l[eé]gie'),
 ('rachmaninoff-melodie', 'Mélodie, Op. 3 No. 3', op(3, 3)),
 ('rachmaninoff-serenade', 'Sérénade, Op. 3 No. 5', op(3, 5)),
 ('rachmaninoff-polichinelle', 'Polichinelle, Op. 3 No. 4', op(3, 4) + r'|polichinelle'),
 ('rachmaninoff-italian-polka', 'Italian Polka', r'italian polka'),
 ('rachmaninoff-moment-musical-4', 'Moment musical, Op. 16 No. 4', op(16, 4)),
 ('rachmaninoff-etude-tableau-39-5', 'Étude-tableau, Op. 39 No. 5', op(39, 5)),
 ('rachmaninoff-lilacs', 'Lilacs, Op. 21 No. 5', r'lilacs|' + op(21, 5)),
 ('rachmaninoff-oriental-sketch', 'Oriental Sketch', r'oriental sketch'),
 ('rachmaninoff-prelude-e-flat', 'Prelude in E-flat, Op. 23 No. 6', op(23, 6)),
])
add('grieg', 'Romantic', [
 ('grieg-morning-mood', 'Morning Mood (Peer Gynt)', r'morning|morgenstemning'),
 ('grieg-solveig', 'Solveig’s Song', r'solveig'),
 ('grieg-anitra', 'Anitra’s Dance', r'anitra'),
 ('grieg-ases-death', 'Åse’s Death', r'[aå]a?se.?s death|aases tod'),
 ('grieg-arietta', 'Arietta, Op. 12 No. 1', r'arietta|' + op(12, 1)),
 ('grieg-wedding-day', 'Wedding Day at Troldhaugen', r'troldhaugen|wedding day'),
 ('grieg-march-trolls', 'March of the Trolls', r'march of the (dwarfs|trolls)|trolltog'),
 ('grieg-waltz-12-2', 'Waltz, Op. 12 No. 2', op(12, 2)),
 ('grieg-elfin-dance', 'Elfin Dance, Op. 12 No. 4', r'elfin dance|' + op(12, 4)),
 ('grieg-notturno', 'Notturno, Op. 54 No. 4', r'notturno|' + op(54, 4)),
 ('grieg-butterfly', 'Butterfly, Op. 43 No. 1', r'butterfly|papillon|' + op(43, 1)),
 ('grieg-to-spring', 'To Spring, Op. 43 No. 6', r'to spring|' + op(43, 6)),
 ('grieg-piano-concerto', 'Piano Concerto in A minor · opening', r'concerto|' + op(16)),
 ('grieg-holberg', 'Holberg Suite · Praeludium', r'holberg'),
 ('grieg-norwegian-dance', 'Norwegian Dance No. 2', r'norwegian dance'),
 ('grieg-watchmans-song', 'Watchman’s Song, Op. 12 No. 3', op(12, 3) + r'|watchman'),
 ('grieg-melody-38-3', 'Melody, Op. 38 No. 3', op(38, 3)),
 ('grieg-folksong-12-5', 'Folk Song, Op. 12 No. 5', op(12, 5)),
 ('grieg-national-song', 'National Song, Op. 12 No. 8', op(12, 8)),
 ('grieg-puck', 'Puck (Kobold), Op. 71 No. 3', r'puck|kobold'),
])
add('dvorak', 'Romantic', [
 ('dvorak-new-world-largo', 'Largo from the New World Symphony (Goin’ Home)', r'new world|largo|goin.? home|symphony (no\.? ?)?9'),
 ('dvorak-humoresque', 'Humoresque, Op. 101 No. 7', r'humoresque|humoreske'),
 ('dvorak-songs-mother', 'Songs My Mother Taught Me', r'songs my mother'),
 ('dvorak-slavonic-dance', 'Slavonic Dance', r'slavonic'),
 ('dvorak-rusalka', 'Song to the Moon (Rusalka)', r'rusalka|song to the moon'),
])
add('saint-saens', 'Romantic', [
 ('saint-saens-swan', 'The Swan (Carnival of the Animals)', r'swan|cygne'),
 ('saint-saens-danse-macabre', 'Danse macabre', r'danse macabre'),
 ('saint-saens-aquarium', 'Aquarium (Carnival of the Animals)', r'aquarium'),
 ('saint-saens-organ-symphony', 'Organ Symphony · finale', r'symphony (no\.? ?)?3|organ symphony'),
 ('saint-saens-lion', 'Royal March of the Lion', r'lion'),
 ('saint-saens-elephant', 'The Elephant', r'elephant'),
 ('saint-saens-mon-coeur', 'Mon cœur s’ouvre à ta voix', r'mon c(oe|œ)ur'),
])
add('bizet', 'Opera & ballet', [
 ('bizet-habanera', 'Habanera (Carmen)', r'habanera'),
 ('bizet-toreador', 'Toreador Song (Carmen)', r'toreador'),
 ('bizet-carmen-prelude', 'Prelude to Carmen', r'carmen.*(prelude|overture|ouverture)|(prelude|overture).*carmen'),
 ('bizet-farandole', 'Farandole (L’Arlésienne)', r'farandole'),
 ('bizet-pearl-fishers', 'Au fond du temple saint (The Pearl Fishers)', r'pearl fishers|p[eê]cheurs de perles|au fond du temple'),
 ('bizet-seguidilla', 'Seguidilla (Carmen)', r'seguidilla'),
 ('bizet-entracte', 'Entr’acte to Act III (Carmen)', r'entr.acte'),
])
add('verdi', 'Opera & ballet', [
 ('verdi-la-donna', 'La donna è mobile (Rigoletto)', r'donna [eè] mobile'),
 ('verdi-brindisi', 'Brindisi (La traviata)', r'brindisi|libiamo'),
 ('verdi-va-pensiero', 'Va, pensiero (Nabucco)', r'va,? pensiero|nabucco|hebrew slaves'),
 ('verdi-triumphal-march', 'Triumphal March (Aida)', r'aida|triumphal march'),
 ('verdi-anvil', 'Anvil Chorus (Il trovatore)', r'anvil|trovatore'),
 ('verdi-dies-irae', 'Dies irae (Requiem)', r'dies irae'),
])
add('puccini', 'Opera & ballet', [
 ('puccini-o-mio-babbino', 'O mio babbino caro', r'babbino'),
 ('puccini-nessun-dorma', 'Nessun dorma', r'nessun dorma'),
 ('puccini-un-bel-di', 'Un bel dì vedremo', r'un bel d'),
 ('puccini-musetta', 'Musetta’s Waltz', r'musetta|quando m.en vo'),
 ('puccini-humming-chorus', 'Humming Chorus (Madama Butterfly)', r'humming chorus'),
])
add('rossini', 'Opera & ballet', [
 ('rossini-william-tell', 'William Tell Overture · finale', r'william tell|guillaume tell|guglielmo tell'),
 ('rossini-barber', 'Barber of Seville · Largo al factotum', r'factotum|barber of seville|barbiere'),
 ('rossini-barber-overture', 'Overture to The Barber of Seville', r'barber.*overture|overture.*barber'),
 ('rossini-thieving-magpie', 'The Thieving Magpie Overture', r'magpie|gazza ladra'),
])
add('wagner', 'Opera & ballet', [
 ('wagner-bridal-chorus', 'Bridal Chorus (Here Comes the Bride)', r'bridal chorus|here comes the bride|lohengrin'),
 ('wagner-valkyries', 'Ride of the Valkyries', r'valkyr|walk[uü]re'),
 ('wagner-tannhauser', 'Pilgrims’ Chorus (Tannhäuser)', r'tannh[aä]user|pilgrim'),
 ('wagner-evening-star', 'Song to the Evening Star', r'evening star'),
 ('wagner-tristan', 'Prelude to Tristan und Isolde', r'tristan'),
])
add('strauss2', 'Opera & ballet', [
 ('strauss-blue-danube', 'The Blue Danube', r'blue danube|blauen donau'),
 ('strauss-radetzky', 'Radetzky March (Johann Strauss I)', r'radetzky'),
 ('strauss-tales-vienna-woods', 'Tales from the Vienna Woods', r'vienna woods|wienerwald'),
 ('strauss-emperor-waltz', 'Emperor Waltz', r'emperor waltz|kaiser.?walzer'),
 ('strauss-pizzicato', 'Pizzicato Polka', r'pizzicato'),
 ('strauss-tritsch', 'Tritsch-Tratsch-Polka', r'tritsch'),
 ('strauss-fledermaus', 'Die Fledermaus Overture', r'fledermaus'),
 ('strauss-voices-spring', 'Voices of Spring', r'voices of spring|fr[uü]hlingsstimmen'),
])
add('offenbach', 'Opera & ballet', [
 ('offenbach-can-can', 'Can-Can (Galop infernal)', r'can.?can|galop infernal|orpheus'),
 ('offenbach-barcarolle', 'Barcarolle (The Tales of Hoffmann)', r'barcarolle|hoffmann'),
])
add('elgar', 'Romantic', [
 ('elgar-pomp-1', 'Pomp and Circumstance March No. 1', r'pomp'),
 ('elgar-nimrod', 'Nimrod (Enigma Variations)', r'nimrod|enigma'),
 ('elgar-salut', 'Salut d’amour', r'salut d.amour'),
 ('elgar-chanson-de-matin', 'Chanson de matin', r'chanson de matin'),
])
add('holst', 'Impressionist & modern', [
 ('holst-jupiter', 'Jupiter (The Planets) · “Thaxted” theme', r'jupiter|thaxted'),
 ('holst-mars', 'Mars, the Bringer of War', r'\bmars\b'),
 ('holst-venus', 'Venus, the Bringer of Peace', r'venus'),
 ('holst-in-the-bleak', 'In the Bleak Midwinter', '$^'),
])
add('mussorgsky', 'Romantic', [
 ('mussorgsky-promenade', 'Promenade (Pictures at an Exhibition)', r'promenade'),
 ('mussorgsky-great-gate', 'The Great Gate of Kiev', r'great gate|kiev|kyiv'),
 ('mussorgsky-bald-mountain', 'Night on Bald Mountain', r'bald mountain'),
 ('mussorgsky-old-castle', 'The Old Castle', r'old castle|vecchio castello'),
 ('mussorgsky-gnome', 'Gnomus', r'gnom'),
 ('mussorgsky-tear', 'A Tear', r'a tear|larme'),
])
add('rimsky', 'Romantic', [
 ('rimsky-bumblebee', 'Flight of the Bumblebee', r'bumble'),
 ('rimsky-scheherazade', 'Scheherazade · The Young Prince and Princess', r'scheherazade|sheherazade'),
 ('rimsky-hindu-song', 'Song of India', r'song of india|hindu'),
])
add('borodin', 'Romantic', [('borodin-polovtsian', 'Polovtsian Dances · Gliding Dance of the Maidens', r'polovtsian|stranger in paradise'), ('borodin-steppes', 'In the Steppes of Central Asia', r'steppes')])
add('scriabin', 'Romantic', [
 ('scriabin-etude-2-1', 'Étude in C-sharp minor, Op. 2 No. 1', op(2, 1)),
 ('scriabin-etude-8-12', 'Étude in D-sharp minor, Op. 8 No. 12', op(8, 12)),
 ('scriabin-prelude-11-1', 'Prelude in C, Op. 11 No. 1', op(11, 1)),
 ('scriabin-prelude-left-hand', 'Prelude for the Left Hand, Op. 9 No. 1', op(9, 1)),
 ('scriabin-prelude-11-4', 'Prelude in E minor, Op. 11 No. 4', op(11, 4)),
 ('scriabin-prelude-16-1', 'Prelude in B, Op. 16 No. 1', op(16, 1)),
 ('scriabin-sonata-2', 'Sonata No. 2 · first movement', op(19)),
 ('scriabin-etude-42-5', 'Étude in C-sharp minor, Op. 42 No. 5', op(42, 5)),
])
add('joplin', 'Ragtime & early jazz', [
 ('joplin-solace', 'Solace', r'solace'),
 ('joplin-elite-syncopations', 'Elite Syncopations', r'elite syncopations'),
 ('joplin-easy-winners', 'The Easy Winners', r'easy winners'),
 ('joplin-pineapple', 'Pineapple Rag', r'pineapple'),
 ('joplin-bethena', 'Bethena (A Concert Waltz)', r'bethena'),
 ('joplin-ragtime-dance', 'The Ragtime Dance', r'ragtime dance'),
 ('joplin-peacherine', 'Peacherine Rag', r'peacherine'),
 ('joplin-gladiolus', 'Gladiolus Rag', r'gladiolus'),
 ('joplin-weeping-willow', 'Weeping Willow', r'weeping willow'),
 ('joplin-original-rags', 'Original Rags', r'original rags'),
 ('joplin-sunflower-slow-drag', 'Sunflower Slow Drag', r'sunflower'),
 ('joplin-palm-leaf', 'Palm Leaf Rag', r'palm leaf'),
 ('joplin-magnetic', 'Magnetic Rag', r'magnetic'),
 ('joplin-stoptime', 'Stoptime Rag', r'stoptime|stop.time'),
 ('joplin-swipesy', 'Swipesy', r'swipesy'),
 ('joplin-wall-street', 'Wall Street Rag', r'wall street'),
 ('joplin-cascades', 'The Cascades', r'cascades'),
 ('joplin-chrysanthemum', 'The Chrysanthemum', r'chrysanthemum'),
 ('joplin-fig-leaf', 'Fig Leaf Rag', r'fig leaf'),
 ('joplin-euphonic', 'Euphonic Sounds', r'euphonic'),
 ('joplin-strenuous-life', 'The Strenuous Life', r'strenuous'),
 ('joplin-heliotrope', 'Heliotrope Bouquet', r'heliotrope'),
 ('joplin-rose-leaf', 'Rose Leaf Rag', r'rose leaf'),
 ('joplin-kismet', 'Kismet Rag', r'kismet'),
 ('joplin-country-club', 'Country Club', r'country club'),
 ('joplin-paragon', 'Paragon Rag', r'paragon'),
 ('joplin-leola', 'Leola', r'leola'),
 ('joplin-binks', 'Binks’ Waltz', r'binks'),
 ('joplin-entertainer-easy', 'The Entertainer · easy version', r'entertainer.*(easy|simplified|beginner)'),
])
add('gershwin', 'Ragtime & early jazz', [
 ('gershwin-rhapsody-blue', 'Rhapsody in Blue · themes', r'rhapsody in blue'),
 ('gershwin-prelude-1', 'Prelude No. 1', r'prelude (no\.? ?)?1|preludes? for piano'),
 ('gershwin-prelude-2', 'Prelude No. 2', r'prelude (no\.? ?)?2'),
 ('gershwin-prelude-3', 'Prelude No. 3', r'prelude (no\.? ?)?3'),
 ('gershwin-swanee', 'Swanee', r'swanee'),
 ('gershwin-american-paris', 'An American in Paris · themes', r'american in paris'),
 ('gershwin-rialto', 'Rialto Ripples', r'rialto'),
 ('gershwin-i-got-rhythm', 'I Got Rhythm', r'i got rhythm'),
 ('gershwin-somebody-loves-me', 'Somebody Loves Me', r'somebody loves me'),
 ('gershwin-the-man-i-love', 'The Man I Love', r'man i love'),
 ('gershwin-fascinating', 'Fascinating Rhythm', r'fascinating rhythm'),
 ('gershwin-embraceable', 'Embraceable You', r'embraceable'),
 ('gershwin-sweet-and-lowdown', 'Sweet and Low-Down', r'sweet and low'),
 ('gershwin-strike-up', 'Strike Up the Band', r'strike up the band'),
 ('gershwin-sk-wonderful', '’S Wonderful', r'.?s wonderful'),
 ('gershwin-lady-be-good', 'Oh, Lady Be Good!', r'lady be good'),
])
add('foster', 'Americana & early popular', [
 ('foster-oh-susanna', 'Oh! Susanna', r'susanna|susannah'),
 ('foster-camptown', 'Camptown Races', r'camptown'),
 ('foster-beautiful-dreamer', 'Beautiful Dreamer', r'beautiful dreamer'),
 ('foster-old-folks', 'Old Folks at Home (Swanee River)', r'old folks at home|swanee river'),
 ('foster-kentucky', 'My Old Kentucky Home', r'kentucky'),
 ('foster-jeanie', 'Jeanie with the Light Brown Hair', r'jeanie'),
 ('foster-hard-times', 'Hard Times Come Again No More', r'hard times'),
 ('foster-old-black-joe', 'Old Black Joe', '$^'),
 ('foster-some-folks', 'Some Folks', r'some folks'),
 ('foster-gentle-annie', 'Gentle Annie', r'gentle annie'),
])
add('sousa', 'Americana & early popular', [
 ('sousa-stars-stripes', 'The Stars and Stripes Forever', r'stars and stripes'),
 ('sousa-washington-post', 'The Washington Post', r'washington post'),
 ('sousa-liberty-bell', 'The Liberty Bell', r'liberty bell'),
 ('sousa-semper-fidelis', 'Semper Fidelis', r'semper fidelis'),
 ('sousa-el-capitan', 'El Capitan', r'el capitan'),
 ('sousa-thunderer', 'The Thunderer', r'thunderer'),
])
add('burgmuller', 'Classical', [
 ('burgmuller-progress', 'Progress, Op. 100 No. 6', op(100, 6) + r'|progr[eè]s'),
 ('burgmuller-clear-stream', 'The Clear Stream, Op. 100 No. 7', op(100, 7) + r'|clear stream|courant limpide'),
 ('burgmuller-gracefulness', 'Gracefulness, Op. 100 No. 8', op(100, 8) + r'|gr[aâ]ce'),
 ('burgmuller-hunting', 'The Chase, Op. 100 No. 9', op(100, 9) + r'|la chasse'),
 ('burgmuller-tender-flower', 'Tender Flower, Op. 100 No. 10', op(100, 10) + r'|tendre fleur'),
 ('burgmuller-wagtail', 'The Wagtail, Op. 100 No. 11', op(100, 11) + r'|bergeronnette|wagtail'),
 ('burgmuller-farewell', 'Farewell, Op. 100 No. 12', op(100, 12) + r'|l.adieu'),
 ('burgmuller-consolation', 'Consolation, Op. 100 No. 13', op(100, 13)),
 ('burgmuller-styrienne', 'La Styrienne, Op. 100 No. 14', op(100, 14) + r'|styrienne'),
 ('burgmuller-sweet-sorrow', 'Sweet Sorrow, Op. 100 No. 16', op(100, 16) + r'|douce plainte'),
 ('burgmuller-chatterbox', 'The Chatterbox, Op. 100 No. 17', op(100, 17) + r'|babillarde'),
 ('burgmuller-agitation', 'Restlessness, Op. 100 No. 18', op(100, 18) + r'|inqui[eé]tude'),
 ('burgmuller-ave-maria', 'Ave Maria, Op. 100 No. 19', op(100, 19)),
 ('burgmuller-tarantella', 'Tarantella, Op. 100 No. 20', op(100, 20) + r'|tarentelle'),
 ('burgmuller-harmony-angels', 'Harmony of the Angels, Op. 100 No. 21', op(100, 21) + r'|harmonie des anges'),
 ('burgmuller-barcarolle', 'Barcarolle, Op. 100 No. 22', op(100, 22)),
 ('burgmuller-return', 'The Return, Op. 100 No. 23', op(100, 23) + r'|le retour'),
 ('burgmuller-swallow', 'The Swallow, Op. 100 No. 24', op(100, 24) + r'|hirondelle'),
 ('burgmuller-knight', 'The Knight Errant, Op. 100 No. 25', op(100, 25) + r'|chevaleresque'),
 ('burgmuller-tarantelle', 'Arabesque, Op. 100 No. 2 · easy', '$^'),
])
add('czerny', 'Classical', [
 ('czerny-599', 'Practical Method, Op. 599 · selected study', op(599)),
 ('czerny-299', 'School of Velocity, Op. 299 No. 1', op(299)),
 ('czerny-740', 'Art of Finger Dexterity, Op. 740', op(740)),
 ('czerny-849', 'Études, Op. 849', op(849)),
])
add('gurlitt', 'Classical', [('gurlitt-the-fair', 'The Fair, Op. 101', r'the fair|' + op(101)), ('gurlitt-night-journey', 'Night Journey', r'night journey'), ('gurlitt-sonatina', 'Sonatina in C, Op. 214', r'sonatina|' + op(214))])
add('kuhlau', 'Classical', [('kuhlau-sonatina-20-1', 'Sonatina in C, Op. 20 No. 1', op(20, 1)), ('kuhlau-sonatina-55-1', 'Sonatina in C, Op. 55 No. 1', op(55, 1)), ('kuhlau-sonatina-55-3', 'Sonatina in C, Op. 55 No. 3', op(55, 3))])
add('diabelli', 'Classical', [('diabelli-sonatina-151', 'Sonatina, Op. 151', op(151)), ('diabelli-sonatina-168', 'Sonatina, Op. 168', op(168))])
add('lemoine', 'Classical', [('lemoine-study-37', 'Study, Op. 37', op(37))])
add('duvernoy', 'Classical', [('duvernoy-176', 'Study, Op. 176', op(176))])
add('streabbog', 'Classical', [('streabbog-gaily-chanting', 'Gaily Chanting Waltz', r'gaily chanting|chanting waltz'), ('streabbog-sunny-morning', 'A Sunny Morning', r'sunny morning')])
add('ellmenreich', 'Romantic', [('ellmenreich-spinning-song', 'Spinning Song', r'spinning song')])
add('lange', 'Romantic', [('lange-flower-song', 'Flower Song, Op. 39', r'flower song|blumenlied')])
add('badarzewska', 'Romantic', [('badarzewska-maidens-prayer', 'A Maiden’s Prayer', r'maiden.?s prayer|pri[eè]re d.une vierge')])
add('godard', 'Romantic', [('godard-berceuse-jocelyn', 'Berceuse from Jocelyn', r'jocelyn|berceuse')])
add('rubinstein', 'Romantic', [('rubinstein-melody-f', 'Melody in F', r'melody in f')])
add('massenet', 'Opera & ballet', [('massenet-meditation', 'Méditation from Thaïs', r'm[eé]ditation|tha[iï]s'), ('massenet-elegie', 'Élégie', r'[eé]l[eé]gie')])
add('gounod', 'Opera & ballet', [('gounod-funeral-marionette', 'Funeral March of a Marionette', r'marionette'), ('gounod-faust-waltz', 'Waltz from Faust', r'faust')])
add('delibes', 'Opera & ballet', [('delibes-flower-duet', 'Flower Duet (Lakmé)', r'flower duet|lakm[eé]'), ('delibes-pizzicati', 'Pizzicati (Sylvia)', r'pizzicat|sylvia'), ('delibes-coppelia', 'Waltz from Coppélia', r'copp[eé]lia')])
add('faure', 'Romantic', [('faure-pavane', 'Pavane, Op. 50', r'pavane'), ('faure-sicilienne', 'Sicilienne, Op. 78', r'sicilienne'), ('faure-apres-un-reve', 'Après un rêve', r'apr[eè]s un r[eê]ve'), ('faure-pie-jesu', 'Pie Jesu (Requiem)', r'pie jesu'), ('faure-dolly', 'Berceuse (Dolly Suite)', r'dolly')])
add('franck', 'Romantic', [('franck-panis', 'Panis angelicus', r'panis angelicus'), ('franck-prelude-fugue', 'Prélude, Choral et Fugue', r'choral')])
add('albeniz', 'Romantic', [('albeniz-asturias', 'Asturias (Leyenda)', r'asturias|leyenda'), ('albeniz-tango', 'Tango in D, Op. 165 No. 2', r'tango'), ('albeniz-granada', 'Granada', r'granada'), ('albeniz-malaguena', 'Malagueña, Op. 165 No. 3', r'malague')])
add('granados', 'Romantic', [('granados-oriental', 'Oriental (Spanish Dance No. 2)', r'oriental'), ('granados-andaluza', 'Andaluza (Spanish Dance No. 5)', r'andaluza|playera|spanish dance'), ('granados-maiden-nightingale', 'The Maiden and the Nightingale', r'nightingale|ruise[ñn]or')])
add('mahler', 'Romantic', [('mahler-adagietto', 'Adagietto (Symphony No. 5)', r'adagietto'), ('mahler-symphony-1', 'Symphony No. 1 · Frère Jacques movement', r'symphony (no\.? ?)?1')])
add('paganini', 'Romantic', [('paganini-caprice-24', 'Caprice No. 24', r'caprice (no\.? ?)?24|24th caprice')])
add('field', 'Romantic', [('field-nocturne-5', 'Nocturne No. 5 in B-flat', r'nocturne')])
add('weber', 'Romantic', [('weber-invitation-dance', 'Invitation to the Dance', r'invitation')])
add('heller', 'Romantic', [('heller-avalanche', 'The Avalanche, Op. 45 No. 2', r'avalanche')])
add('macdowell', 'Romantic', [('macdowell-wild-rose', 'To a Wild Rose', r'wild rose'), ('macdowell-water-lily', 'To a Water Lily', r'water lily')])
add('glinka', 'Romantic', [('glinka-lark', 'The Lark', r'lark'), ('glinka-ruslan', 'Ruslan and Lyudmila Overture', r'ruslan')])
add('lyadov', 'Romantic', [('lyadov-music-box', 'A Musical Snuffbox', r'snuff.?box|music box|tabati[eè]re')])
add('chaminade', 'Romantic', [('chaminade-scarf-dance', 'Scarf Dance', r'scarf dance|pas des [eé]charpes'), ('chaminade-automne', 'Automne', r'automne')])
add('moszkowski', 'Romantic', [('moszkowski-spanish-dance', 'Spanish Dance, Op. 12 No. 1', r'spanish dance|' + op(12, 1)), ('moszkowski-etincelles', 'Étincelles', r'[eé]tincelles')])
add('smetana', 'Romantic', [('smetana-moldau', 'The Moldau (Vltava)', r'moldau|vltava')])
add('ivanovici', 'Romantic', [('ivanovici-waves', 'Waves of the Danube', r'waves of the danube|danube waves')])
add('waldteufel', 'Romantic', [('waldteufel-skaters', 'The Skaters’ Waltz', r'skaters')])
add('rosas', 'Romantic', [('rosas-over-the-waves', 'Over the Waves (Sobre las olas)', r'over the waves|sobre las olas')])
add('jessel', 'Romantic', [('jessel-wooden-soldiers', 'Parade of the Wooden Soldiers', r'wooden soldiers')])
add('fucik', 'Romantic', [('fucik-gladiators', 'Entry of the Gladiators', r'gladiators')])
add('lehar', 'Opera & ballet', [('lehar-merry-widow', 'Merry Widow Waltz', r'merry widow|lustige witwe')])
add('ponchielli', 'Opera & ballet', [('ponchielli-hours', 'Dance of the Hours', r'dance of the hours')])
add('leoncavallo', 'Opera & ballet', [('leoncavallo-vesti', 'Vesti la giubba (Pagliacci)', r'vesti la giubba|pagliacci'), ('leoncavallo-mattinata', 'Mattinata', r'mattinata')])
add('mascagni', 'Opera & ballet', [('mascagni-intermezzo', 'Intermezzo (Cavalleria rusticana)', r'cavalleria|intermezzo')])
add('tarrega', 'Romantic', [('tarrega-recuerdos', 'Recuerdos de la Alhambra', r'recuerdos'), ('tarrega-lagrima', 'Lágrima', r'l[aá]grima'), ('tarrega-gran-vals', 'Gran Vals', r'gran vals')])
add('nazareth', 'Ragtime & early jazz', [('nazareth-odeon', 'Odeon (Tango brasileiro)', r'odeon'), ('nazareth-brejeiro', 'Brejeiro', r'brejeiro')])
add('gottschalk', 'Romantic', [('gottschalk-banjo', 'The Banjo', r'banjo'), ('gottschalk-dying-poet', 'The Dying Poet', r'dying poet')])
add('turk', 'Classical', [('turk-pieces', 'Little pieces for beginners (Türk)', r'.')])
add('reinecke', 'Classical', [('reinecke-sonatina', 'Sonatina, Op. 136', r'sonatin')])
add('alkan', 'Romantic', [('alkan-le-festin', 'Le festin d’Ésope', r'festin')])
add('martini', 'Romantic', [('martini-plaisir', 'Plaisir d’amour', r'plaisir')])
add('tosti', 'Romantic', [('tosti-serenata', 'Serenata', r'serenata'), ('tosti-ideale', 'Ideale', r'ideale')])
add('prokofiev', 'Impressionist & modern', [('prokofiev-oranges-march', 'March from The Love for Three Oranges (1919)', r'three oranges'), ('prokofiev-classical-gavotte', 'Gavotte from the Classical Symphony (1917)', r'classical symphony|gavotte'), ('prokofiev-toccata', 'Toccata, Op. 11 (1912)', op(11) + r'|toccata')])
add('janacek', 'Impressionist & modern', [('janacek-in-the-mists', 'In the Mists', r'in the mists|v mlh')])

# Traditional and anonymous music, and songs whose writers died before 1956 (published before 1931).
add('carol', 'Christmas', [
 ('carol-silent-night', 'Silent Night', r'silent night|stille nacht'),
 ('carol-joy-to-the-world', 'Joy to the World', r'joy to the world'),
 ('carol-o-holy-night', 'O Holy Night (Adolphe Adam)', r'o holy night|minuit,? chr[eé]tiens|cantique de no'),
 ('carol-hark-herald', 'Hark! The Herald Angels Sing', r'hark!?,? the herald'),
 ('carol-o-come-all-ye', 'O Come, All Ye Faithful', r'o come,? all ye faithful|adeste fideles'),
 ('carol-deck-the-halls', 'Deck the Halls', r'deck the hall'),
 ('carol-jingle-bells', 'Jingle Bells', r'jingle bells'),
 ('carol-we-wish-you', 'We Wish You a Merry Christmas', r'we wish you a merry'),
 ('carol-god-rest-ye', 'God Rest Ye Merry, Gentlemen', r'god rest (ye|you) merry'),
 ('carol-first-noel', 'The First Noel', r'first no[eë]l|first nowell'),
 ('carol-away-in-a-manger', 'Away in a Manger', r'away in a manger'),
 ('carol-o-little-town', 'O Little Town of Bethlehem', r'little town of bethlehem'),
 ('carol-what-child', 'What Child Is This?', r'what child is this'),
 ('carol-angels-we-have-heard', 'Angels We Have Heard on High', r'angels we have heard|gloria in excelsis'),
 ('carol-good-king-wenceslas', 'Good King Wenceslas', r'wenceslas'),
 ('carol-carol-of-the-bells', 'Carol of the Bells (Shchedryk, Leontovych)', r'carol of the bells|shchedryk|schedryk'),
 ('carol-o-christmas-tree', 'O Christmas Tree', r'o christmas tree|o tannenbaum'),
 ('carol-up-on-the-housetop', 'Up on the Housetop', r'up on the housetop'),
 ('carol-jolly-old-st-nicholas', 'Jolly Old Saint Nicholas', r'jolly old (st|saint)'),
 ('carol-twelve-days', 'The Twelve Days of Christmas', r'twelve days of christmas|12 days of christmas'),
 ('carol-coventry', 'Coventry Carol', r'coventry'),
 ('carol-bleak-midwinter', 'In the Bleak Midwinter (Holst)', r'bleak midwinter'),
 ('carol-it-came-upon', 'It Came Upon the Midnight Clear', r'it came upon'),
 ('carol-once-in-royal', 'Once in Royal David’s City', r'royal david'),
 ('carol-we-three-kings', 'We Three Kings', r'we three kings'),
 ('carol-go-tell-it', 'Go Tell It on the Mountain', r'go tell it on'),
 ('carol-o-come-emmanuel', 'O Come, O Come, Emmanuel', r'o come,? o come,? emm?anuel|veni emmanuel'),
 ('carol-ding-dong', 'Ding Dong Merrily on High', r'ding dong merrily'),
 ('carol-here-we-come', 'Here We Come A-Wassailing', r'wassail'),
 ('carol-i-saw-three-ships', 'I Saw Three Ships', r'three ships'),
 ('carol-lo-how-a-rose', 'Lo, How a Rose E’er Blooming', r'lo,? how a rose|es ist ein ros'),
 ('carol-holly-ivy', 'The Holly and the Ivy', r'holly and the ivy'),
 ('carol-angels-from-realms', 'Angels from the Realms of Glory', r'realms of glory'),
 ('carol-bring-a-torch', 'Bring a Torch, Jeannette, Isabella', r'bring a torch'),
 ('carol-good-christian-men', 'Good Christian Men, Rejoice', r'good christian (men|friends)|in dulci jubilo'),
 ('carol-huron', 'Huron Carol', r'huron carol|twas in the moon'),
 ('carol-pat-a-pan', 'Pat-a-Pan', r'pat.a.pan'),
 ('carol-il-est-ne', 'Il est né, le divin Enfant', r'il est n[eé]'),
 ('carol-jingle-bells-easy', 'Jingle Bells · easy version', r'jingle bells.*(easy|beginner|simple)'),
 ('carol-o-come-little-children', 'O Come, Little Children', r'little children'),
 ('carol-mary-boy-child', 'Sussex Carol', r'sussex carol|on christmas night all christians'),
 ('carol-we-wish-easy', 'Christmas Medley of Carols', r'christmas (carol )?medley'),
 ('carol-angels-tidings', 'While Shepherds Watched', r'while shepherds watched'),
 ('carol-auld-lang-syne', 'Auld Lang Syne', r'auld lang syne'),
 ('carol-hallelujah-easy', 'Gaudete', r'gaudete'),
 ('carol-infant-holy', 'Infant Holy, Infant Lowly', r'infant holy'),
 ('carol-in-the-bleak-easy', 'Christmas Is Coming', r'christmas is coming'),
 ('carol-jesus-bambino', 'Still, Still, Still', r'still,? still,? still'),
 ('carol-o-holy-night-easy', 'Masters in This Hall', r'masters in this hall'),
])
add('hymn', 'Hymns & spirituals', [
 ('hymn-amazing-grace', 'Amazing Grace', r'amazing grace'),
 ('hymn-be-thou-my-vision', 'Be Thou My Vision', r'be thou my vision'),
 ('hymn-it-is-well', 'It Is Well with My Soul', r'it is well'),
 ('hymn-holy-holy', 'Holy, Holy, Holy', r'holy,? holy,? holy'),
 ('hymn-abide-with-me', 'Abide with Me', r'abide with me'),
 ('hymn-nearer-my-god', 'Nearer, My God, to Thee', r'nearer,? my god'),
 ('hymn-rock-of-ages', 'Rock of Ages', r'rock of ages'),
 ('hymn-what-a-friend', 'What a Friend We Have in Jesus', r'what a friend'),
 ('hymn-come-thou-fount', 'Come, Thou Fount of Every Blessing', r'come,? thou fount'),
 ('hymn-in-the-garden', 'In the Garden', r'in the garden'),
 ('hymn-blessed-assurance', 'Blessed Assurance', r'blessed assurance'),
 ('hymn-a-mighty-fortress', 'A Mighty Fortress Is Our God', r'mighty fortress|feste burg'),
 ('hymn-all-creatures', 'All Creatures of Our God and King', r'all creatures of our god'),
 ('hymn-jesus-loves-me', 'Jesus Loves Me', r'jesus loves me'),
 ('hymn-shall-we-gather', 'Shall We Gather at the River', r'shall we gather'),
 ('hymn-softly-tenderly', 'Softly and Tenderly', r'softly and tenderly'),
 ('hymn-down-to-the-river', 'Down to the River to Pray', r'down to the river to pray|as i went down in the river'),
 ('hymn-swing-low', 'Swing Low, Sweet Chariot', r'swing low'),
 ('hymn-wade-in-the-water', 'Wade in the Water', r'wade in the water'),
 ('hymn-go-down-moses', 'Go Down, Moses', r'go down,? moses'),
 ('hymn-deep-river', 'Deep River', r'deep river'),
 ('hymn-nobody-knows', 'Nobody Knows the Trouble I’ve Seen', r'nobody knows the trouble'),
 ('hymn-were-you-there', 'Were You There', r'were you there'),
 ('hymn-this-little-light', 'This Little Light of Mine', r'this little light'),
 ('hymn-whole-world', 'He’s Got the Whole World in His Hands', r'whole world in his hand'),
 ('hymn-michael-row', 'Michael, Row the Boat Ashore', r'michael,? row'),
 ('hymn-when-the-saints', 'When the Saints Go Marching In', r'when the saints'),
 ('hymn-battle-hymn', 'Battle Hymn of the Republic', r'battle hymn'),
 ('hymn-doxology', 'Doxology (Old Hundredth)', r'doxology|old hundredth|old 100'),
 ('hymn-holy-night-adeste', 'Praise to the Lord, the Almighty', r'praise to the lord'),
 ('hymn-joyful-joyful', 'Joyful, Joyful, We Adore Thee', r'joyful,? joyful'),
 ('hymn-for-the-beauty', 'For the Beauty of the Earth', r'beauty of the earth'),
 ('hymn-crown-him', 'Crown Him with Many Crowns', r'crown him with'),
 ('hymn-o-for-a-thousand', 'O for a Thousand Tongues to Sing', r'thousand tongues'),
 ('hymn-love-divine', 'Love Divine, All Loves Excelling', r'love divine'),
 ('hymn-eternal-father', 'Eternal Father, Strong to Save', r'eternal father'),
 ('hymn-morning-has-broken', 'Morning Has Broken (Bunessan)', r'bunessan'),
 ('hymn-simple-gifts', 'Simple Gifts', r'simple gifts|tis the gift to be simple'),
 ('hymn-i-surrender', 'Kumbaya', r'kum ?ba ?y'),
 ('hymn-sweet-by-and-by', 'In the Sweet By and By', r'sweet by and by'),
 ('hymn-there-is-power', 'There Is Power in the Blood', r'power in the blood'),
 ('hymn-are-you-washed', 'Leaning on the Everlasting Arms', r'leaning on the everlasting'),
 ('hymn-i-need-thee', 'I Need Thee Every Hour', r'i need thee every hour'),
 ('hymn-jerusalem', 'Jerusalem (Parry)', r'^jerusalem|and did those feet'),
 ('hymn-i-vow-to-thee', 'I Vow to Thee, My Country (Thaxted)', r'i vow to thee'),
 ('hymn-steal-away', 'Steal Away', r'steal away'),
 ('hymn-sometimes-feel', 'Sometimes I Feel Like a Motherless Child', r'motherless child'),
 ('hymn-were-climbing', 'We Are Climbing Jacob’s Ladder', r'jacob.?s ladder'),
 ('hymn-there-is-a-balm', 'There Is a Balm in Gilead', r'balm in gilead'),
 ('hymn-onward', 'Onward, Christian Soldiers', r'onward,? christian'),
 ('hymn-the-church-one', 'The Church’s One Foundation', r'church.?s one foundation'),
 ('hymn-all-hail', 'All Hail the Power of Jesus’ Name', r'all hail the power'),
 ('hymn-when-i-survey', 'When I Survey the Wondrous Cross', r'wondrous cross'),
 ('hymn-it-came', 'Be Still, My Soul (Finlandia hymn)', '$^'),
])
add('folk', 'Folk songs of the world', [
 ('folk-greensleeves', 'Greensleeves', r'greensleeves'),
 ('folk-danny-boy', 'Danny Boy (Londonderry Air)', r'danny boy|londonderry'),
 ('folk-scarborough-fair', 'Scarborough Fair', r'scarborough'),
 ('folk-shenandoah', 'Shenandoah', r'shenandoah'),
 ('folk-home-on-the-range', 'Home on the Range', r'home on the range'),
 ('folk-red-river-valley', 'Red River Valley', r'red river valley'),
 ('folk-clementine', 'Oh My Darling, Clementine', r'clementine'),
 ('folk-sakura', 'Sakura Sakura', r'sakura'),
 ('folk-arirang', 'Arirang', r'arirang'),
 ('folk-korobeiniki', 'Korobeiniki', r'korobein|korobushka|tetris'),
 ('folk-kalinka', 'Kalinka', r'kalinka'),
 ('folk-dark-eyes', 'Dark Eyes (Ochi chornye)', r'dark eyes|ochi chorn|black eyes'),
 ('folk-hava-nagila', 'Hava Nagila', r'hava nagila'),
 ('folk-la-cucaracha', 'La Cucaracha', r'cucaracha'),
 ('folk-cielito-lindo', 'Cielito Lindo', r'cielito lindo'),
 ('folk-bella-ciao', 'Bella Ciao', r'bella ciao'),
 ('folk-o-sole-mio', 'O sole mio', r'o sole mio'),
 ('folk-santa-lucia', 'Santa Lucia', r'santa lucia'),
 ('folk-funiculi', 'Funiculì, Funiculà', r'funicul'),
 ('folk-torna-surriento', 'Torna a Surriento', r'surriento|sorrento'),
 ('folk-skye-boat', 'Skye Boat Song', r'skye boat'),
 ('folk-loch-lomond', 'Loch Lomond', r'loch lomond'),
 ('folk-molly-malone', 'Molly Malone', r'molly malone|cockles and mussels'),
 ('folk-water-is-wide', 'The Water Is Wide', r'water is wide|o waly'),
 ('folk-drunken-sailor', 'What Shall We Do with the Drunken Sailor', r'drunken sailor'),
 ('folk-wellerman', 'Wellerman', r'wellerman'),
 ('folk-my-bonnie', 'My Bonnie Lies over the Ocean', r'my bonnie'),
 ('folk-sloop-john-b', 'The John B. Sails', '$^'),
 ('folk-la-paloma', 'La Paloma (Yradier)', r'la paloma'),
 ('folk-la-cumparsita', 'La Cumparsita', r'cumparsita'),
 ('folk-el-choclo', 'El Choclo', r'el choclo'),
 ('folk-estrellita', 'Estrellita (Ponce)', r'estrellita'),
 ('folk-las-mananitas', 'Las Mañanitas', r'ma[ñn]anitas'),
 ('folk-la-bamba', 'La Bamba (traditional)', '$^'),
 ('folk-scotland-the-brave', 'Scotland the Brave', r'scotland the brave'),
 ('folk-irish-washerwoman', 'The Irish Washerwoman', r'irish washerwoman'),
 ('folk-the-minstrel-boy', 'The Minstrel Boy', r'minstrel boy'),
 ('folk-she-moved', 'She Moved Through the Fair', r'she moved through'),
 ('folk-early-one-morning', 'Early One Morning', r'early one morning'),
 ('folk-the-ash-grove', 'The Ash Grove', r'ash grove'),
 ('folk-all-through-night', 'All Through the Night', r'all through the night'),
 ('folk-barbara-allen', 'Barbara Allen', r'barbara allen'),
 ('folk-sur-le-pont', 'Sur le pont d’Avignon', r'pont d.avignon'),
 ('folk-au-clair', 'Au clair de la lune', r'au clair de la lune'),
 ('folk-alouette', 'Alouette', r'alouette'),
 ('folk-la-vie-en', 'À la claire fontaine', r'claire fontaine'),
 ('folk-edelweiss-not', 'Muss i denn', r'muss i denn'),
 ('folk-lorelei', 'Die Lorelei (Silcher)', r'lorelei|loreley'),
 ('folk-du-du', 'Du, du liegst mir im Herzen', r'du,? du liegst'),
 ('folk-ach-du-lieber', 'O du lieber Augustin', r'lieber augustin'),
 ('folk-kookaburra', 'Waltzing Matilda', '$^'),
 ('folk-mo-li-hua', 'Mo Li Hua (Jasmine Flower)', r'mo ?li ?hua|jasmine flower'),
 ('folk-kojo-no-tsuki', 'Kōjō no Tsuki (Taki Rentarō, 1901)', r'k[oō]j[oō] no tsuki|moon over the ruined castle'),
 ('folk-furusato', 'Furusato (1914)', r'furusato'),
 ('folk-ievan-polkka', 'Ievan polkka', r'ievan polkka|ievan polka'),
 ('folk-kalinka-easy', 'Moscow Nights', '$^'),
 ('folk-troika', 'The Peddlers (Korobeiniki) · easy', '$^'),
 ('folk-oh-tannenbaum', 'Hatikvah', r'hatikvah'),
 ('folk-the-parting-glass', 'The Parting Glass', r'parting glass'),
 ('folk-salley-gardens', 'Down by the Salley Gardens', r'salley gardens|sally gardens'),
 ('folk-carrickfergus', 'Carrickfergus', r'carrickfergus'),
 ('folk-black-velvet', 'Star of the County Down', r'county down'),
 ('folk-the-lark', 'The Lark in the Clear Air', r'lark in the clear'),
 ('folk-the-skye', 'Ye Banks and Braes', r'banks and braes'),
 ('folk-flower-of-scotland', 'Comin’ Thro’ the Rye', r'comin.? thro'),
 ('folk-polly-wolly', 'Polly Wolly Doodle', r'polly wolly'),
 ('folk-turkey-in-the-straw', 'Turkey in the Straw', r'turkey in the straw'),
 ('folk-arkansas-traveler', 'Arkansas Traveler', r'arkansas traveler'),
 ('folk-cotton-eye-joe', 'Cotton-Eyed Joe', r'cotton.eye'),
 ('folk-oh-dear', 'Oh, Dear! What Can the Matter Be?', r'what can the matter be'),
 ('folk-bonnie-banks', 'The Blue Bells of Scotland', r'blue bells of scotland'),
 ('folk-ode-easy', 'Erie Canal (Low Bridge)', r'erie canal|low bridge'),
 ('folk-wayfaring', 'Wayfaring Stranger', r'wayfaring stranger'),
 ('folk-house-rising-sun', 'The House of the Rising Sun (traditional)', '$^'),
 ('folk-oh-shenandoah', 'Bound for South Australia', '$^'),
 ('folk-la-golondrina', 'La Golondrina', r'golondrina'),
 ('folk-cielito-easy', 'De Colores', r'de colores'),
 ('folk-guantanamera', 'Las Chiapanecas', r'chiapanecas'),
 ('folk-zum-gali', 'Zum Gali Gali', r'zum gali'),
 ('folk-tumbalalaika', 'Tumbalalaika', r'tumbalalaika'),
 ('folk-sarasponda', 'Ah! vous dirai-je, maman', '$^'),
 ('folk-ievan', 'Hej Sokoły', r'hej,? soko'),
 ('folk-oy-u-luzi', 'Oy u luzi chervona kalyna', r'chervona kalyna'),
 ('folk-nkosi', 'Nkosi Sikelel’ iAfrika', r'nkosi sikelel'),
])
add('children', 'Children’s songs', [
 ('kids-mary-lamb', 'Mary Had a Little Lamb', r'mary had a little lamb'),
 ('kids-row-row', 'Row, Row, Row Your Boat', r'row,? row,? row'),
 ('kids-london-bridge', 'London Bridge Is Falling Down', r'london bridge'),
 ('kids-old-macdonald', 'Old MacDonald Had a Farm', r'old mac ?donald'),
 ('kids-hot-cross-buns', 'Hot Cross Buns', r'hot cross buns'),
 ('kids-itsy-bitsy', 'The Itsy Bitsy Spider', r'itsy.bitsy|incy.wincy'),
 ('kids-yankee-doodle', 'Yankee Doodle', r'yankee doodle(?! boy| dandy)'),
 ('kids-happy-birthday', 'Happy Birthday to You (Mildred and Patty Hill)', r'happy birthday'),
 ('kids-wheels-on-bus', 'The Wheels on the Bus', '$^'),
 ('kids-pop-goes-weasel', 'Pop Goes the Weasel', r'pop goes the weasel'),
 ('kids-ring-around', 'Ring a Ring o’ Roses', r'ring around the ros|ring a ring'),
 ('kids-hickory-dickory', 'Hickory Dickory Dock', r'hickory dickory'),
 ('kids-humpty-dumpty', 'Humpty Dumpty', r'humpty dumpty'),
 ('kids-jack-and-jill', 'Jack and Jill', r'jack and jill'),
 ('kids-lavenders-blue', 'Lavender’s Blue', r'lavender.?s blue'),
 ('kids-oranges-lemons', 'Oranges and Lemons', r'oranges and lemons'),
 ('kids-pease-porridge', 'Pease Porridge Hot', r'pease porridge'),
 ('kids-this-old-man', 'This Old Man', r'this old man'),
 ('kids-the-muffin-man', 'The Muffin Man', r'muffin man'),
 ('kids-hush-little-baby', 'Hush, Little Baby', r'hush,? little baby'),
 ('kids-rock-a-bye', 'Rock-a-bye Baby', r'rock.a.bye'),
 ('kids-skip-to-my-lou', 'Skip to My Lou', r'skip to my lou'),
 ('kids-oh-where', 'Oh Where, Oh Where Has My Little Dog Gone', r'little dog gone'),
 ('kids-bingo', 'Bingo', r'^bingo|b-i-n-g-o'),
 ('kids-head-shoulders', 'Head, Shoulders, Knees and Toes', r'head,? shoulders'),
 ('kids-if-youre-happy', 'If You’re Happy and You Know It', r'happy and you know it'),
 ('kids-five-little-ducks', 'Alle meine Entchen', r'alle meine entchen'),
 ('kids-haenschen', 'Hänschen klein', r'h[aä]e?nschen klein'),
 ('kids-kuckuck', 'Kuckuck, Kuckuck', r'kuckuck'),
 ('kids-brother-john', 'Are You Sleeping (Frère Jacques) · two hands', '$^'),
 ('kids-ah-vous-dirai', 'Baa, Baa, Black Sheep', r'baa,? baa'),
 ('kids-pussy-cat', 'Sing a Song of Sixpence', r'song of sixpence'),
 ('kids-polly-kettle', 'Polly Put the Kettle On', r'polly put the kettle'),
 ('kids-three-blind-mice', 'Three Blind Mice', r'three blind mice'),
 ('kids-the-farmer', 'The Farmer in the Dell', r'farmer in the dell'),
 ('kids-oats-peas', 'Here We Go Round the Mulberry Bush', r'mulberry bush'),
 ('kids-ten-little', 'Lightly Row', r'lightly row'),
 ('kids-go-tell-aunt-rhody', 'Go Tell Aunt Rhody', r'aunt rhody'),
 ('kids-oh-when', 'Merrily We Roll Along', r'merrily we roll'),
 ('kids-au-clair-easy', 'Brahms’ Lullaby · easy', '$^'),
 ('kids-twinkle-variations', 'Twinkle, Twinkle, Little Star · with variations', r'twinkle.*variation'),
 ('kids-chopsticks', 'Chopsticks (The Celebrated Chop Waltz, 1877)', r'chopsticks|chop waltz'),
 ('kids-heart-and-soul', 'Lullaby and Good Night · easy', '$^'),
])
add('americana', 'Americana & early popular', [
 ('pop-take-me-out', 'Take Me Out to the Ball Game (1908)', r'take me out to the ball'),
 ('pop-let-me-call-you-sweetheart', 'Let Me Call You Sweetheart (1910)', r'let me call you sweetheart'),
 ('pop-daisy-bell', 'Daisy Bell (Bicycle Built for Two, 1892)', r'daisy bell|bicycle built for two'),
 ('pop-after-the-ball', 'After the Ball (1892)', r'after the ball'),
 ('pop-in-the-good-old-summertime', 'In the Good Old Summertime (1902)', r'good old summertime'),
 ('pop-meet-me-st-louis', 'Meet Me in St. Louis, Louis (1904)', r'meet me in st'),
 ('pop-give-my-regards', 'Give My Regards to Broadway (1904)', r'give my regards'),
 ('pop-yankee-doodle-boy', 'The Yankee Doodle Boy (1904)', r'yankee doodle (boy|dandy)'),
 ('pop-grand-old-flag', 'You’re a Grand Old Flag (1906)', r'grand old flag'),
 ('pop-over-there', 'Over There (1917)', r'^over there'),
 ('pop-silvery-moon', 'By the Light of the Silvery Moon (1909)', r'silvery moon'),
 ('pop-old-mill-stream', 'Down by the Old Mill Stream (1910)', r'old mill stream'),
 ('pop-irish-eyes', 'When Irish Eyes Are Smiling (1912)', r'irish eyes'),
 ('pop-wild-irish-rose', 'My Wild Irish Rose (1899)', r'wild irish rose'),
 ('pop-bill-bailey', 'Bill Bailey, Won’t You Please Come Home (1902)', r'bill bailey'),
 ('pop-the-sidewalks', 'The Sidewalks of New York (1894)', r'sidewalks of new york'),
 ('pop-charleston', 'Charleston (1923)', r'^the charleston|^charleston'),
 ('pop-aura-lee', 'Aura Lee (1861)', r'aura lee'),
 ('pop-grandfathers-clock', 'My Grandfather’s Clock (1876)', r'grandfather.?s clock'),
 ('pop-the-band-played-on', 'The Band Played On (1895)', r'band played on'),
 ('pop-sweet-rosie', 'Sweet Rosie O’Grady (1896)', '$^'),
 ('pop-dixie', 'Dixie (1859)', '$^'),
 ('pop-star-spangled', 'The Star-Spangled Banner', r'star.spangled'),
 ('pop-america-beautiful', 'America the Beautiful (Ward)', r'america,? the beautiful'),
 ('pop-my-country', 'My Country, ’Tis of Thee', r'my country.? .?tis'),
 ('pop-marine-hymn', 'Marines’ Hymn', r'marines.? hymn|halls of montezuma'),
 ('pop-anchors-aweigh', 'Anchors Aweigh (1906)', r'anchors aweigh'),
 ('pop-the-caissons', 'When Johnny Comes Marching Home', r'johnny comes marching'),
 ('pop-yellow-rose', 'The Yellow Rose of Texas', r'yellow rose of texas'),
 ('pop-in-the-shade', 'In the Shade of the Old Apple Tree (1905)', r'old apple tree'),
 ('pop-alexanders-not', 'Shine Little Glow-Worm (Lincke, 1902)', '$^'),
 ('pop-oh-you-beautiful-doll', 'Oh, You Beautiful Doll (1911)', r'beautiful doll'),
 ('pop-toot-toot-tootsie', 'The Darktown Strutters’ Ball', '$^'),
 ('pop-after-youve-gone', 'After You’ve Gone (1918)', '$^'),
 ('pop-memories', 'Memories (Egbert Van Alstyne, 1915)', '$^'),
 ('pop-carolina-in-the-morning', 'Pack Up Your Troubles (1915)', r'pack up your troubles'),
 ('pop-its-a-long-way', 'It’s a Long Way to Tipperary (1912)', r'tipperary'),
 ('pop-keep-the-home-fires', 'Keep the Home Fires Burning (1914)', r'home fires burning'),
 ('pop-roses-of-picardy', 'Roses of Picardy (1916)', '$^'),
 ('pop-hello-dolly-not', 'The Maple Leaf Forever', r'maple leaf forever'),
 ('pop-o-canada', 'O Canada (Lavallée, 1880)', r'o canada'),
 ('pop-la-marseillaise', 'La Marseillaise', r'marseillaise'),
 ('pop-god-save', 'God Save the King', r'god save the (king|queen)'),
 ('pop-rule-britannia', 'Rule, Britannia!', r'rule,? britannia'),
 ('pop-colonel-bogey', 'Colonel Bogey March (1914)', '$^'),
 ('pop-the-entertainer-2', 'Twelfth Street Rag (1914)', r'twelfth street|12th street'),
 ('pop-tiger-rag', 'Tiger Rag (1917)', '$^'),
 ('pop-dill-pickles', 'Dill Pickles Rag (1906)', r'dill pickles'),
 ('pop-black-and-white-rag', 'Black and White Rag (1908)', r'black and white rag'),
 ('pop-grizzly-bear', 'Frog Legs Rag (James Scott)', r'frog legs'),
 ('pop-climax-rag', 'Climax Rag (James Scott)', r'climax rag'),
 ('pop-great-scott', 'Grace and Beauty (James Scott)', r'grace and beauty'),
 ('pop-carolina-shout', 'Carolina Shout (James P. Johnson, 1921)', r'carolina shout'),
 ('pop-whistling-rufus', 'Whistling Rufus (1899)', r'whistling rufus'),
 ('pop-hello-ma-baby', 'Smoky Mokes (1899)', r'smoky mokes'),
 ('pop-st-louis-tickle', 'St. Louis Tickle (1904)', r'st\.? louis tickle'),
 ('pop-kitten', 'Ragtime Nightingale', '$^'),
 ('pop-limehouse-not', 'Hiawatha (Neil Moret, 1901)', r'hiawatha'),
 ('pop-tea-for-two-not', 'Hello! Ma Baby', '$^'),
])
