# Public-domain composers (died 1955 or earlier, so their music is free in the US and in
# life+70 countries). Pattern matches PDMX composer/artist/title text.
C = [
 # (key, display name, died, regex)
 ('bach', 'Johann Sebastian Bach', 1750, r'\bj\.?\s*s\.?\s*bach\b|johann sebastian bach|\bbach\b(?!.*\b(c\.?\s*p\.?\s*e|carl philipp|w\.?\s*f\.?|wilhelm friedemann|anna magdalena|jan-ole|johann christian)\b)|\bbwv\b'),
 ('beethoven', 'Ludwig van Beethoven', 1827, r'beethoven'),
 ('mozart', 'Wolfgang Amadeus Mozart', 1791, r'mozart(?!.*leopold)|\bk\.?\s?\d{2,3}\b.*mozart'),
 ('chopin', 'Frédéric Chopin', 1849, r'chopin'),
 ('liszt', 'Franz Liszt', 1886, r'\bliszt'),
 ('schubert', 'Franz Schubert', 1828, r'schubert'),
 ('schumann', 'Robert Schumann', 1856, r'(?<!clara )schumann'),
 ('clara', 'Clara Schumann', 1896, r'clara (wieck|schumann)'),
 ('mendelssohn', 'Felix Mendelssohn', 1847, r'mendelssohn'),
 ('brahms', 'Johannes Brahms', 1897, r'brahms'),
 ('tchaikovsky', 'Pyotr Ilyich Tchaikovsky', 1893, r't[cs]ha[ij]?[ck]ovsk|tchaikowsky|chaikovsky|tschaikowsky'),
 ('debussy', 'Claude Debussy', 1918, r'debussy'),
 ('satie', 'Erik Satie', 1925, r'\bsatie\b'),
 ('ravel', 'Maurice Ravel', 1937, r'\bravel\b'),
 ('rachmaninoff', 'Sergei Rachmaninoff', 1943, r'ra[ck]h?maninov|rachmaninoff|rachmaninow'),
 ('grieg', 'Edvard Grieg', 1907, r'\bgrieg'),
 ('dvorak', 'Antonín Dvořák', 1904, r'dvo[rř][aá]k'),
 ('handel', 'George Frideric Handel', 1759, r'h[aä]e?ndel'),
 ('vivaldi', 'Antonio Vivaldi', 1741, r'vivaldi'),
 ('pachelbel', 'Johann Pachelbel', 1706, r'pachelbel'),
 ('haydn', 'Joseph Haydn', 1809, r'\bhaydn'),
 ('scarlatti', 'Domenico Scarlatti', 1757, r'scarlatti'),
 ('clementi', 'Muzio Clementi', 1832, r'clementi'),
 ('czerny', 'Carl Czerny', 1857, r'czerny'),
 ('burgmuller', 'Friedrich Burgmüller', 1874, r'burgm[uü]e?ller'),
 ('joplin', 'Scott Joplin', 1917, r'\bjoplin\b'),
 ('gershwin', 'George Gershwin', 1937, r'gershwin'),
 ('saint-saens', 'Camille Saint-Saëns', 1921, r'saint[- ]sa[eë]ns'),
 ('bizet', 'Georges Bizet', 1875, r'\bbizet'),
 ('verdi', 'Giuseppe Verdi', 1901, r'\bverdi\b'),
 ('puccini', 'Giacomo Puccini', 1924, r'puccini'),
 ('rossini', 'Gioachino Rossini', 1868, r'rossini'),
 ('wagner', 'Richard Wagner', 1883, r'\bwagner\b'),
 ('strauss2', 'Johann Strauss II', 1899, r'johann strauss|j\.\s*strauss|strauss (ii|jr)|blue danube|blauen donau|radetzky'),
 ('offenbach', 'Jacques Offenbach', 1880, r'offenbach'),
 ('elgar', 'Edward Elgar', 1934, r'\belgar\b'),
 ('holst', 'Gustav Holst', 1934, r'\bholst\b'),
 ('mussorgsky', 'Modest Mussorgsky', 1881, r'mussorgsk|moussorgsk'),
 ('rimsky', 'Nikolai Rimsky-Korsakov', 1908, r'rimsky'),
 ('borodin', 'Alexander Borodin', 1887, r'borodin'),
 ('scriabin', 'Alexander Scriabin', 1915, r'scriabin|skryabin'),
 ('albeniz', 'Isaac Albéniz', 1909, r'alb[eé]niz'),
 ('granados', 'Enrique Granados', 1916, r'granados'),
 ('faure', 'Gabriel Fauré', 1924, r'faur[eé]\b'),
 ('massenet', 'Jules Massenet', 1912, r'massenet'),
 ('gounod', 'Charles Gounod', 1893, r'gounod'),
 ('delibes', 'Léo Delibes', 1891, r'delibes'),
 ('franck', 'César Franck', 1890, r'c[eé]sar franck'),
 ('mahler', 'Gustav Mahler', 1911, r'\bmahler\b'),
 ('bruckner', 'Anton Bruckner', 1896, r'bruckner'),
 ('purcell', 'Henry Purcell', 1695, r'purcell'),
 ('couperin', 'François Couperin', 1733, r'couperin'),
 ('rameau', 'Jean-Philippe Rameau', 1764, r'rameau'),
 ('telemann', 'Georg Philipp Telemann', 1767, r'telemann'),
 ('albinoni', 'Tomaso Albinoni', 1751, r'albinoni'),
 ('boccherini', 'Luigi Boccherini', 1805, r'boccherini'),
 ('paganini', 'Niccolò Paganini', 1840, r'paganini(?!.*(liszt|rachmaninov|rachmaninoff|brahms))'),
 ('field', 'John Field', 1837, r'john field'),
 ('weber', 'Carl Maria von Weber', 1826, r'carl maria von weber|c\.?\s*m\.?\s*von weber'),
 ('heller', 'Stephen Heller', 1888, r'stephen heller'),
 ('gurlitt', 'Cornelius Gurlitt', 1901, r'gurlitt'),
 ('kuhlau', 'Friedrich Kuhlau', 1832, r'kuhlau'),
 ('diabelli', 'Anton Diabelli', 1858, r'diabelli'),
 ('streabbog', 'Jean Louis Streabbog', 1886, r'streabbog'),
 ('reinecke', 'Carl Reinecke', 1910, r'reinecke'),
 ('lemoine', 'Henry Lemoine', 1854, r'lemoine'),
 ('duvernoy', 'Jean-Baptiste Duvernoy', 1880, r'duvernoy'),
 ('beyer', 'Ferdinand Beyer', 1863, r'ferdinand beyer|\bbeyer\b'),
 ('hanon', 'Charles-Louis Hanon', 1900, r'\bhanon\b'),
 ('foster', 'Stephen Foster', 1864, r'stephen (c\.? )?foster'),
 ('sousa', 'John Philip Sousa', 1932, r'\bsousa\b'),
 ('lamb', 'Joseph Lamb', 1960, r'$^'),
 ('macdowell', 'Edward MacDowell', 1908, r'macdowell'),
 ('badarzewska', 'Tekla Bądarzewska', 1861, r'b[aą]darzewska|maiden.?s prayer'),
 ('ketelbey', 'Albert Ketèlbey', 1959, r'$^'),
 ('sibelius', 'Jean Sibelius', 1957, r'$^'),
 ('glinka', 'Mikhail Glinka', 1857, r'glinka'),
 ('lyadov', 'Anatoly Lyadov', 1914, r'[lj]iadov|lyadov'),
 ('arensky', 'Anton Arensky', 1906, r'arensky'),
 ('godard', 'Benjamin Godard', 1895, r'godard'),
 ('chaminade', 'Cécile Chaminade', 1944, r'chaminade'),
 ('janacek', 'Leoš Janáček', 1928, r'jan[aá][cč]ek'),
 ('smetana', 'Bedřich Smetana', 1884, r'smetana'),
 ('ivanovici', 'Iosif Ivanovici', 1902, r'ivanovici|waves of the danube'),
 ('waldteufel', 'Émile Waldteufel', 1915, r'waldteufel|skaters.? waltz'),
 ('lehar', 'Franz Lehár', 1948, r'leh[aá]r'),
 ('rubinstein', 'Anton Rubinstein', 1894, r'anton rubinstein|rubinstein.*melody in f'),
 ('ponchielli', 'Amilcare Ponchielli', 1886, r'ponchielli'),
 ('leoncavallo', 'Ruggero Leoncavallo', 1919, r'leoncavallo'),
 ('mascagni', 'Pietro Mascagni', 1945, r'mascagni'),
 ('khachaturian', 'Aram Khachaturian', 1978, r'$^'),
 ('prokofiev', 'Sergei Prokofiev', 1953, r'prokofiev|prokofieff'),
 ('stravinsky', 'Igor Stravinsky', 1971, r'$^'),
 ('nazareth', 'Ernesto Nazareth', 1934, r'nazareth'),
 ('tarrega', 'Francisco Tárrega', 1909, r't[aá]rrega'),
 ('alkan', 'Charles-Valentin Alkan', 1888, r'\balkan\b'),
 ('moszkowski', 'Moritz Moszkowski', 1925, r'moszkowski'),
 ('mompou', 'Federico Mompou', 1987, r'$^'),
 ('ellmenreich', 'Albert Ellmenreich', 1905, r'ellmenreich|spinning song'),
 ('lange', 'Gustav Lange', 1889, r'gustav lange'),
 ('oesten', 'Theodor Oesten', 1870, r'oesten'),
 ('spindler', 'Fritz Spindler', 1905, r'spindler'),
 ('poldini', 'Ede Poldini', 1957, r'$^'),
 ('jessel', 'Leon Jessel', 1942, r'jessel|parade of the wooden soldiers'),
 ('fucik', 'Julius Fučík', 1916, r'fu[cč][ií]k|entry of the gladiators|entrance of the gladiators'),
 ('rosas', 'Juventino Rosas', 1894, r'juventino rosas|over the waves|sobre las olas'),
 ('lincke', 'Paul Lincke', 1946, r'$^'),
 ('chabrier', 'Emmanuel Chabrier', 1894, r'chabrier'),
 ('tosti', 'Francesco Paolo Tosti', 1916, r'\btosti\b'),
 ('martini', 'Jean-Paul-Égide Martini', 1816, r'plaisir d.amour'),
 ('caccini', 'Giulio Caccini', 1618, r'$^'),
 ('cui', 'César Cui', 1918, r'c[eé]sar cui'),
 ('gottschalk', 'Louis Moreau Gottschalk', 1869, r'gottschalk'),
 ('hummel', 'Johann Nepomuk Hummel', 1837, r'\bhummel\b'),
 ('kabalevsky', 'Dmitri Kabalevsky', 1987, r'$^'),
 ('tiersen', 'Yann Tiersen', 9999, r'$^'),
 ('holzmann', 'Abe Holzmann', 1939, r'$^'),
 ('turk', 'Daniel Gottlob Türk', 1813, r'd\.?\s*g\.?\s*t[uü]e?rk|daniel gottlob t'),
 ('petzold', 'Christian Petzold', 1733, r'petzold|minuet in g.*(anh|bwv anh)'),
 ('anna-magdalena', 'Anna Magdalena Notebook', 1750, r'anna magdalena'),
]
