# Manual review of candidate matches: must/forbid patterns on the candidate's text, and title fixes.
FIX = {
 'bach-prelude-c-minor': dict(title='Prelude and Fugue in C minor, BWV 847'),
 'bach-fugue-c-minor': dict(skip=True),
 'bach-prelude-d-major': dict(title='Prelude and Fugue in D major, BWV 850'),
 'bach-prelude-bwv-933': dict(must=r'933'),
 'bach-minuet-g-minor': dict(must=r'g minor|115'),
 'bach-ave-maria': dict(forbid=r'instrument'),
 'handel-water-music-hornpipe': dict(title='Minuet from Water Music, HWV 350'),
 'handel-passacaglia': dict(title='Passacaglia (Handel–Halvorsen)'),
 'purcell-hornpipe': dict(must=r'purcell.*hornpipe|hornpipe.*purcell', forbid=r'hole in the wall'),
 'rameau-tambourin': dict(title='Tambourins I & II (Dardanus)'),
 'albinoni-adagio': dict(forbid=r'fabian'),
 'mozart-k330': dict(title='Sonata in C, K. 330 · third movement', must=r'3rd|third|iii\b'),
 'mozart-k283': dict(title='Sonata in G, K. 283 · second movement (Andante)', must=r'andante'),
 'mozart-k457': dict(forbid=r'expozice|exposition'),
 'mozart-k576': dict(title='Sonata in D, K. 576 · third movement (Allegretto)', must=r'allegretto'),
 'mozart-figaro-overture': dict(forbid=r'liszt|fantas'),
 'mozart-piano-concerto-21': dict(title='Piano Concerto No. 21 · first movement', must=r'movement i\b|1st|first'),
 'mozart-lullaby': dict(title='Wiegenlied (Bernhard Flies, long credited to Mozart)', composer='Bernhard Flies'),
 'beethoven-moonlight-2': dict(forbid=r'first and second|1st and 2nd'),
 'beethoven-pathetique-1': dict(forbid=r'twist'),
 'beethoven-sonatina-g': dict(title='Sonatina in F, Anh. 5 No. 2', must=r'\bin f\b|f major'),
 'beethoven-bagatelle-119': dict(title='Bagatelle, Op. 119 No. 3', must=r'n\.?o?\.? ?3\b'),
 'beethoven-symphony-9': dict(forbid=r'inno|ode to joy|an die freude'),
 'beethoven-emperor-concerto': dict(title='Piano Concerto No. 5 “Emperor” · Adagio (excerpt)'),
 'schubert-serenade': dict(title='Ständchen (Serenade), D. 957 · arr. Liszt', must=r'liszt|st[aä]e?ndchen|serenade'),
 'schubert-impromptu-90-2': dict(forbid=r'a part of'),
 'schubert-erlkonig': dict(title='Erlkönig, D. 328 · arr. Liszt'),
 'schubert-standchen-waltz': dict(title='German Dance No. 1 in A-flat'),
 'chopin-andante-spianato': dict(forbid=r'rachmaninov|rachmaninoff|variations on'),
 'chopin-sonata-3-finale': dict(forbid=r'part'),
 'liszt-mephisto': dict(title='Mephisto Waltz No. 3', must=r'no\.? ?3'),
 'brahms-rhapsody-79-2': dict(title='Rhapsody in B minor, Op. 79 No. 1', must=r'b minor'),
 'tchaikovsky-symphony-6': dict(title='Symphony No. 6 “Pathétique” · fourth movement', must=r'4th|fourth|iv\b'),
 'tchaikovsky-symphony-5': dict(title='Symphony No. 5 · third movement (Valse)', must=r'3rd|valse|waltz'),
 'grieg-piano-concerto': dict(title='Piano Concerto in A minor · first-movement cadenza', must=r'cadenza'),
 'saint-saens-swan': dict(forbid=r'lead sheet|jazz'),
 'rossini-barber': dict(title='The Barber of Seville · themes'),
 'rossini-thieving-magpie': dict(title='Solemn March from The Thieving Magpie', must=r'march'),
 'wagner-bridal-chorus': dict(title='Elsa’s Procession to the Cathedral (Lohengrin)', must=r'elsa'),
 'wagner-tannhauser': dict(title='Tannhäuser Overture', must=r'overture'),
 'wagner-tristan': dict(title='Liebestod (Tristan und Isolde)', must=r'transfiguration|liebestod'),
 'burgmuller-progress': dict(must=r'progr|no\.? ?6\b'),
 'czerny-599': dict(title='Study, Op. 599 No. 63', must=r'63'),
 'czerny-740': dict(title='Étude in G minor, Op. 740 No. 50', must=r'50'),
 'czerny-849': dict(title='Étude in G minor, Op. 849 No. 26', must=r'26'),
 'lemoine-study-37': dict(title='Études enfantines, Op. 37 No. 4', must=r'no\.? ?4\b'),
 'duvernoy-176': dict(title='Elementary Study, Op. 176 No. 1', must=r'etude 1\b|no\.? ?1\b'),
 'ellmenreich-spinning-song': dict(must=r'ellmenreich'),
 'gounod-faust-waltz': dict(title='Soldiers’ Chorus (Faust)', must=r'soldat|soldier'),
 'field-nocturne-5': dict(title='Nocturne No. 10', must=r'no\.? ?10'),
 'leoncavallo-vesti': dict(forbid=r'tenor'),
 'carol-silent-night': dict(forbid=r'roseau|rousseau'),
 'carol-jingle-bells': dict(forbid=r'jazz'),
 'carol-o-come-little-children': dict(must=r'o come'),
 'carol-o-holy-night-easy': dict(must=r'masters'),
 'carol-here-we-come': dict(forbid=r'vaughan'),
 'hymn-it-is-well': dict(must=r'with my soul|it is well with'),
 'hymn-in-the-garden': dict(must=r'in the garden'),
 'hymn-jerusalem': dict(forbid=r'ridge'),
 'hymn-i-surrender': dict(forbid=r'peter paul'),
 'hymn-steal-away': dict(forbid=r'seconds'),
 'folk-scarborough-fair': dict(forbid=r'simon|garfunkel'),
 'folk-shenandoah': dict(forbid=r'falls'),
 'folk-clementine': dict(forbid=r'autry'),
 'folk-sakura': dict(must=r'sakura,? sakura|^sakura\b'),
 'folk-korobeiniki': dict(forbid=r'tetris'),
 'folk-la-cumparsita': dict(forbid=r'tutorial|parte'),
 'folk-estrellita': dict(must=r'estrellita(?!s)'),
 'folk-ach-du-lieber': dict(title='O du lieber Augustin'),
 'kids-london-bridge': dict(must=r'london bridge'),
 'kids-this-old-man': dict(must=r'this old man'),
 'kids-rock-a-bye': dict(forbid=r'jig'),
 'kids-pussy-cat': dict(must=r'sixpence'),
 'kids-twinkle-variations': dict(forbid=r'suzuki'),
 'pop-over-there': dict(forbid=r'gould'),
 'pop-charleston': dict(forbid=r'gals'),
 'pop-the-entertainer-2': dict(forbid=r'roy clark'),
 'pop-limehouse-not': dict(forbid=r'hornpipe'),
}
GLOBAL_FORBID = r'lead sheet|for c instruments|tutorial|\(babcock\)|- maltbie|- adam geibel|- wm\. j\.|- will l\.|- chas\. h\.|- i\. allan|- w\. carroll|- arthur wilton|- rev\. j|- j\. lincoln|\(geibel\)|\(kirkpatrick\)|\(thompson\)|vaughan williams|carl philipp|c\.\s?p\.\s?e\.|emanuel bach|friedemann'
