# Extra works chosen by hand from the most-viewed public-domain piano scores in PDMX.
# (exact PDMX title, composer key, display title, shelf, composer display override or None)
P = [
 ("Bach Fugue in G Minor BWV 578 (Piano solo)", 'bach', 'Little Fugue in G minor, BWV 578', 'Baroque', None),
 ("Beethoven (Eroica) Symphony No. 3 in E-flat Major (1st movement) Piano", 'beethoven', 'Symphony No. 3 “Eroica” · first movement', 'Classical', None),
 ("Maurice Ravel's La Valse (Piano solo)", 'ravel', 'La Valse', 'Impressionist & modern', None),
 ("Schumann Carnaval - No. 12 Chopin (Piano solo)", 'schumann', '“Chopin” from Carnaval, Op. 9', 'Romantic', None),
 ("Little Prelude Number 2 in C Minor - BWV 934", 'bach', 'Little Prelude in C minor, BWV 934', 'Baroque', None),
 ("Schubert Piano Trio in E Flat Major 2nd Movement (Piano solo)", 'schubert', 'Piano Trio in E-flat, D. 929 · Andante con moto', 'Romantic', None),
 ("Beethoven Symphony No. 5 (2nd movement) Piano solo", 'beethoven', 'Symphony No. 5 · second movement', 'Classical', None),
 ("Bach Fugue in G Minor BWV 542 (Piano solo)", 'bach', 'Great Fugue in G minor, BWV 542', 'Baroque', None),
 ("Swan Lake Op. 20 Act IV No.29 (Scene Finale)", 'tchaikovsky', 'Swan Lake · Final Scene', 'Opera & ballet', None),
 ("Beethoven Symphony No. 5 (4th movement finale) Piano solo", 'beethoven', 'Symphony No. 5 · finale', 'Classical', None),
 ("Beethoven Symphony No 5 (3rd Movement) Piano solo", 'beethoven', 'Symphony No. 5 · third movement', 'Classical', None),
 ("Beethoven Symphony No. 6 Pastoral (5th movement) Piano solo", 'beethoven', 'Symphony No. 6 “Pastoral” · Shepherd’s Song', 'Classical', None),
 ("Rachmaninoff 2nd Piano Concerto (3rd movement excerpts) Piano solo", 'rachmaninoff', 'Piano Concerto No. 2 · finale (excerpts)', 'Romantic', None),
 ("Czerny - School Of Velocity - Op. 299 No. 3", 'czerny', 'School of Velocity, Op. 299 No. 3', 'Classical', None),
 ("Czerny - School Of Velocity - Op. 299 No. 2", 'czerny', 'School of Velocity, Op. 299 No. 2', 'Classical', None),
 ("Beethoven Symphony No. 7 (1st movement) Piano solo", 'beethoven', 'Symphony No. 7 · first movement', 'Classical', None),
 ("Beethoven Symphony No. 7 (4th movement) Piano solo", 'beethoven', 'Symphony No. 7 · finale', 'Classical', None),
 ("Das Deutschlandlied", 'haydn', 'Emperor Hymn (Gott erhalte Franz den Kaiser)', 'Classical', None),
 ("Wagner Siegfried's Funeral March from Götterdämmerung (Piano solo)", 'wagner', 'Siegfried’s Funeral March (Götterdämmerung)', 'Opera & ballet', None),
 ("J. S. Bach: Prelude and Fugue in C Minor BWV 549", 'bach', 'Prelude and Fugue in C minor, BWV 549', 'Baroque', None),
 ("Haydn: Sonata in G Major HOB.XVI:8", 'haydn', 'Sonata in G, Hob. XVI:8', 'Classical', None),
 ("Fugue in E Minor BWV 914 By Johann Sebastian Bach", 'bach', 'Fugue from Toccata in E minor, BWV 914', 'Baroque', None),
 ("A Study in Double Notes (Thirds) by Carl Czerny", 'czerny', 'Study in Double Notes (Thirds)', 'Classical', None),
 ("Nocturne (F.Chopin Op.55. No.2)", 'chopin', 'Nocturne in E-flat, Op. 55 No. 2', 'Romantic', None),
 ("Beethoven Symphony No. 9 (1st Movement) Piano solo", 'beethoven', 'Symphony No. 9 · first movement', 'Classical', None),
 ("J. S. Bach - Partita No.1 - B flat major - Menuet 1 - BWV 825", 'bach', 'Menuet I from Partita No. 1, BWV 825', 'Baroque', None),
 ("J.S. Bach - English Suite no.3 in G minor BWV 808", 'bach', 'English Suite No. 3 in G minor, BWV 808', 'Baroque', None),
 ("Minuet in G major (Haydn)", 'haydn', 'Minuet in G', 'Classical', None),
 ("Beethoven Symphony No 1 (1st Movement) Piano solo", 'beethoven', 'Symphony No. 1 · first movement', 'Classical', None),
 ("Schumann Toccata Op. 7 (Piano solo)", 'schumann', 'Toccata, Op. 7', 'Romantic', None),
 ("Saint-Saëns 2nd Piano Concerto (1st Movement) Piano solo", 'saint-saens', 'Piano Concerto No. 2 · first movement', 'Romantic', None),
 ("Introduction and Rondo Capriccioso - C. Saint-Saëns arr. C. Debussy", 'saint-saens', 'Introduction and Rondo capriccioso · arr. Debussy', 'Romantic', None),
 ("Chopin - Piano Sonata 2 in Bb Minor", 'chopin', 'Sonata No. 2 in B-flat minor, Op. 35', 'Romantic', None),
 ("8. Waltz Childrens Album Tchaikovsky", 'tchaikovsky', 'Waltz, Op. 39 No. 8 (Children’s Album)', 'Romantic', None),
 ("The Nutcracker Overture (Piano)", 'tchaikovsky', 'Miniature Overture (The Nutcracker)', 'Opera & ballet', None),
 ("J.S. Bach Choralvorspiel Ich ruf' zu dir Herr BWV 639 (Arrt F. Busoni)", 'bach', 'Ich ruf’ zu dir, Herr Jesu Christ, BWV 639 · arr. Busoni', 'Baroque', None),
 ("Russian Folk Song Op 107 No. 3 by Ludwig van Beethoven", 'beethoven', 'Russian Folk Song, Op. 107 No. 3', 'Classical', None),
 ("L'amour est un oiseau rebelle", 'bizet', 'Habanera (Carmen)', 'Opera & ballet', None),
 ("Mendelssohn Songs Without Words (No. 3) Piano solo", 'mendelssohn', 'Hunting Song, Op. 19 No. 3', 'Romantic', None),
 ("Songs without Words No.7 Op.30 No.1", 'mendelssohn', 'Song without Words, Op. 30 No. 1', 'Romantic', None),
 ("Vivaldi - RV 297 L'Hiver - Allegro non molto (Piano)", 'vivaldi', 'Winter from The Four Seasons · first movement', 'Baroque', None),
 ("Burlesque - G Major", 'mozart', 'Burlesque in G (Notebook for Nannerl)', 'Classical', 'Leopold Mozart'),
 ("Thème du 1er mouvement de la sonate K.331", 'mozart', 'Sonata in A, K. 331 · theme', 'Classical', None),
 ("Chopin Fugue in A minor; B.144", 'chopin', 'Fugue in A minor, B. 144', 'Romantic', None),
 ("Scarlatti D. Keyboard Sonata in B minor K.87", 'scarlatti', 'Sonata in B minor, K. 87', 'Baroque', None),
 ("Fantasy Fantasia in C minor BWV 906", 'bach', 'Fantasia in C minor, BWV 906', 'Baroque', None),
 ("Lyric Piece Book IV No. 2 Album-Leaf", 'grieg', 'Album Leaf, Op. 47 No. 2', 'Romantic', None),
 ("Petite suite (C.Debussy)", 'debussy', 'Petite Suite', 'Impressionist & modern', None),
 ("Wagner Overture to the Opera Parsifal (Piano solo)", 'wagner', 'Prelude to Parsifal', 'Opera & ballet', None),
 ("Wolfgang Amadeus Mozart - Morgen kommt der Weihnachtsmann", 'carol', 'Morgen kommt der Weihnachtsmann', 'Christmas', 'Traditional'),
 ("Le Gibet - No.2 from Gaspard de la Nuit - Maurice Ravel", 'ravel', 'Le Gibet (Gaspard de la nuit)', 'Impressionist & modern', None),
 ("Romance d amour (origianal)", 'folk', 'Romance (Spanish Romance)', 'Folk songs of the world', 'Anonymous'),
 ("Bach Sinfonia 15 BWV 801 in B minor", 'bach', 'Sinfonia No. 15 in B minor, BWV 801', 'Baroque', None),
 ("Johann Sebastian Bach - Partita No. 3 BWV 1006 Prelude", 'bach', 'Prelude from Partita No. 3 for violin, BWV 1006', 'Baroque', None),
 ("Pomp and Circumstance March No. 4 in G Major (Piano Transcription)", 'elgar', 'Pomp and Circumstance March No. 4', 'Romantic', None),
 ("Frédéric Chopin: Étude in E-flat major Op.10 No.11 Arpeggio", 'chopin', 'Étude in E-flat, Op. 10 No. 11', 'Romantic', None),
 ("March in D Minor by Carl Czerny", 'czerny', 'March in D minor', 'Classical', None),
 ("Wolfgang Amadeus Mozart - Piano Concerto No. 21 Movement II Andante 2", 'mozart', 'Piano Concerto No. 21 · Andante (“Elvira Madigan”)', 'Classical', None),
 ("Komm lieber Mai", 'mozart', 'Longing for Spring (Komm, lieber Mai), K. 596', 'Classical', None),
 ("La Violette", 'streabbog', 'La Violette', 'Classical', None),
 ("Beethoven Piano Sonata No. 29 1st Movement", 'beethoven', 'Hammerklavier Sonata, Op. 106 · first movement', 'Classical', None),
 ("Impertinence HWV 494 - Haendel", 'handel', 'Impertinence, HWV 494', 'Baroque', None),
 ("Agitato by Burgmuller", 'burgmuller', 'Agitato', 'Classical', None),
 ("Vals nº 9 D. 969", 'schubert', 'Waltz No. 9, D. 969', 'Romantic', None),
 ("Debussy - Préludes - Book I - II", 'debussy', 'Voiles (Préludes, Book I No. 2)', 'Impressionist & modern', None),
 ("Debussy - Préludes - Book I - I", 'debussy', 'Danseuses de Delphes (Préludes, Book I No. 1)', 'Impressionist & modern', None),
 ("Debussy - Préludes - Book I - IV", 'debussy', 'Les sons et les parfums (Préludes, Book I No. 4)', 'Impressionist & modern', None),
 ("Bruyères", 'debussy', 'Bruyères (Préludes, Book II No. 5)', 'Impressionist & modern', None),
 ("Feux d'Artifice", 'debussy', 'Feux d’artifice (Préludes, Book II No. 12)', 'Impressionist & modern', None),
 ("Les collines d'Anacapri", 'debussy', 'Les collines d’Anacapri', 'Impressionist & modern', None),
 ("Sarabande (C.Debussy. Pour le piano. No.2. )", 'debussy', 'Sarabande (Pour le piano)', 'Impressionist & modern', None),
 ("Bach js capriccio bwv 992", 'bach', 'Capriccio on the Departure of a Beloved Brother, BWV 992', 'Baroque', None),
 ("MOZART: Piano Concerto No. 19 in F major - Allegro. More accurate repr", 'mozart', 'Piano Concerto No. 19 · Allegro', 'Classical', None),
 ("Rachmaninoff - Moment Musical No 3 in B Minor", 'rachmaninoff', 'Moment musical in B minor, Op. 16 No. 3', 'Romantic', None),
 ("Rachmaninoff - Moment Musical No 5 in Db Major", 'rachmaninoff', 'Moment musical in D-flat, Op. 16 No. 5', 'Romantic', None),
 ("Lohengrin Overture Piano", 'wagner', 'Prelude to Lohengrin', 'Opera & ballet', None),
 ("J.S. Bach Sinfonia No. 3 in D Major (3-part Invention)", 'bach', 'Sinfonia No. 3 in D, BWV 789', 'Baroque', None),
 ("Scarlatti Sonata K 208", 'scarlatti', 'Sonata in A, K. 208', 'Baroque', None),
 ("Scherzo No.4 (F.Chopin Op.54)", 'chopin', 'Scherzo No. 4 in E, Op. 54', 'Romantic', None),
 ("Invention No. 3 in D Major", 'bach', 'Invention No. 3 in D, BWV 774', 'Baroque', None),
 ("Kind im Einschlummern - Kinderszenen No 12 (child falling asleep)", 'schumann', 'Child Falling Asleep, Op. 15 No. 12', 'Romantic', None),
 ("Beethoven - Sonata Op. 31 No. 17 - 3rd Movement - Tempest", 'beethoven', 'Tempest Sonata · third movement', 'Classical', None),
 ("Franz Liszt - Consolations I.", 'liszt', 'Consolation No. 1', 'Romantic', None),
 ("Spanish Dance [Chocolate] (From The Nutcracker)", 'tchaikovsky', 'Spanish Dance (Chocolate)', 'Opera & ballet', None),
 ("Scriabin's Nocturne for the left hand", 'scriabin', 'Nocturne for the Left Hand, Op. 9 No. 2', 'Romantic', None),
 ("Czerny - The Art Of Finger Dexterity (Op. 740) - No. 1", 'czerny', 'The Art of Finger Dexterity, Op. 740 No. 1', 'Classical', None),
 ("Ridicolosamente", 'prokofiev', 'Ridicolosamente (Visions fugitives No. 10, 1917)', 'Impressionist & modern', None),
 ("John Field - Nocturne in E flat major Molto moderato", 'field', 'Nocturne No. 1 in E-flat', 'Romantic', None),
 ("J.P. Rameau Suite en Sol Nr 4 La Poule (The Hen)", 'rameau', 'La Poule (The Hen)', 'Baroque', None),
 ("The Seasons Op. 37a March Song of the lark", 'tchaikovsky', 'March · Song of the Lark (The Seasons)', 'Romantic', None),
 ("The Seasons Op. 37a February Carnival", 'tchaikovsky', 'February · Carnival (The Seasons)', 'Romantic', None),
 ("Tchaikovsky-April", 'tchaikovsky', 'April · Snowdrop (The Seasons)', 'Romantic', None),
 ("Saint Saens le carnaval des animaux final piano solo version", 'saint-saens', 'Finale (Carnival of the Animals)', 'Romantic', None),
 ("Frédéric Chopin: Étude in D-flat major Op.25 No.8 Sixths", 'chopin', 'Étude in D-flat, Op. 25 No. 8', 'Romantic', None),
 ("Beethoven Sonata 32 (Opus 111) Mvt 2", 'beethoven', 'Sonata No. 32, Op. 111 · Arietta', 'Classical', None),
 ("Invocation from Liszt's Harmonies poétiques et religieuses III.", 'liszt', 'Invocation (Harmonies poétiques et religieuses)', 'Romantic', None),
 ("The Nutcracker 1. Decoration of the Christmas tree (Remaster Piano)", 'tchaikovsky', 'Decorating the Christmas Tree (The Nutcracker)', 'Opera & ballet', None),
 ("Sonata in D Minor K.213 (The Lover) Domenico Scarlatti", 'scarlatti', 'Sonata in D minor, K. 213', 'Baroque', None),
 ("Die Meistersinger Von Nürnberg - Vorspiel (R.Wagner - H.v.Bülow)", 'wagner', 'Prelude to Die Meistersinger', 'Opera & ballet', None),
 ("Edward Grieg - Zug der Zwerge", 'grieg', 'March of the Dwarfs, Op. 54 No. 3', 'Romantic', None),
 ("Chopin Nocturne Op.48 No.2", 'chopin', 'Nocturne in F-sharp minor, Op. 48 No. 2', 'Romantic', None),
 ("J.S. Bach Choralvorspiel ''Nun komm' der Heiden Heiland'' (Arrt F. Bus", 'bach', 'Nun komm, der Heiden Heiland, BWV 659 · arr. Busoni', 'Baroque', None),
 ("Première Valse oubliée", 'liszt', 'Valse oubliée No. 1', 'Romantic', None),
 ("March of the Wooden Soldiers Op.39 No5", 'tchaikovsky', 'March of the Wooden Soldiers, Op. 39 No. 5', 'Romantic', None),
 ("Carioca (1913)", 'nazareth', 'Carioca (1913)', 'Ragtime & early jazz', None),
 ("Franz Liszt: Hungarian Rhapsody No.10 in E major", 'liszt', 'Hungarian Rhapsody No. 10', 'Romantic', None),
 ("Haydn - Sonata in C minor HOB XVI/20 Movement I", 'haydn', 'Sonata in C minor, Hob. XVI:20 · first movement', 'Classical', None),
 ("Scriabin: Sonata No. 4 in F Major (Movement I)", 'scriabin', 'Sonata No. 4 · first movement', 'Romantic', None),
 ("Casta diva", 'chopin', 'Casta diva (Norma)', 'Opera & ballet', 'Vincenzo Bellini'),
 ("Preludio from Transcendental Études", 'liszt', 'Preludio (Transcendental Étude No. 1)', 'Romantic', None),
 ("Schumann - Album for the Young Op. 68 No. 6 The Poor Orphan-Child", 'schumann', 'Poor Orphan Child, Op. 68 No. 6', 'Romantic', None),
 ("Alexander March (Beethoven)", 'beethoven', 'Alexander March', 'Classical', None),
 ("Der Tod und das Mädchen D.531", 'schubert', 'Death and the Maiden, D. 531', 'Romantic', None),
 ("Études d'exécution transcendante S.139/2 Molto Vivace", 'liszt', 'Transcendental Étude No. 2 in A minor', 'Romantic', None),
 ("Franz Liszt: Transcendental Étude No.10 in F minor Appassionata", 'liszt', 'Transcendental Étude No. 10 in F minor', 'Romantic', None),
 ("Prelude op.11 no. 1 (Anatoly Lyadov)", 'lyadov', 'Prelude, Op. 11 No. 1', 'Romantic', None),
 ("Menuet g-Moll (BWV 842)", 'bach', 'Minuet in G minor, BWV 842', 'Baroque', None),
 ("Fauré - Dolly Suite No. 3: Le Jardin de Dolly", 'faure', 'Le Jardin de Dolly (Dolly Suite)', 'Romantic', None),
 ("Schumann- Schlummerlied", 'schumann', 'Slumber Song, Op. 124 No. 16', 'Romantic', None),
 ("Alexander Scriabin: Piano Sonata No.5 Op.53", 'scriabin', 'Sonata No. 5, Op. 53', 'Romantic', None),
 ("Minuet in F Major BWV 116 Anh. 113 by JS Bach", 'bach', 'Minuet in F, BWV Anh. 113', 'Baroque', None),
 ("J. S. Bach - Invention No. 5 in Eb-Major BWV 776 (real audio)", 'bach', 'Invention No. 5 in E-flat, BWV 776', 'Baroque', None),
 ("Liszt's Arrangement of Handel's Sarabande and Chaconne (Piano solo)", 'liszt', 'Sarabande and Chaconne (after Handel)', 'Romantic', None),
 ("Grande fantaisie triomphale sur l'hymne national brésilien Op.69 (Gott", 'gottschalk', 'Grande fantaisie triomphale, Op. 69', 'Romantic', None),
 ("Battle Cry of Freedom - Gottschalk (1865)", 'gottschalk', 'The Battle Cry of Freedom', 'Americana & early popular', None),
 ("Rachmaninoff - Études-Tableaux Op. 39 no. 2", 'rachmaninoff', 'Étude-tableau, Op. 39 No. 2', 'Romantic', None),
 ("Prelude and Fugue 3 - OpenWTC", 'bach', 'Prelude and Fugue in C-sharp major, BWV 848', 'Baroque', None),
 ("Prelude and Fugue 6 - OpenWTC", 'bach', 'Prelude and Fugue in D minor, BWV 851', 'Baroque', None),
 ("Prelude and Fugue 10 - OpenWTC", 'bach', 'Prelude and Fugue in E minor, BWV 855', 'Baroque', None),
 ("Prelude and Fugue 21 - OpenWTC", 'bach', 'Prelude and Fugue in B-flat major, BWV 866', 'Baroque', None),
 ("Prelude and Fugue 24 - OpenWTC", 'bach', 'Prelude and Fugue in B minor, BWV 869', 'Baroque', None),
 ("Prelude and Fugue 12 - OpenWTC", 'bach', 'Prelude and Fugue in F minor, BWV 857', 'Baroque', None),
]
