# Composer credit for traditional / song entries (id -> name). Defaults by category below.
WHO = {
 'carol-silent-night': 'Franz Xaver Gruber', 'carol-joy-to-the-world': 'Lowell Mason (after Handel)', 'carol-o-holy-night': 'Adolphe Adam',
 'carol-hark-herald': 'Felix Mendelssohn', 'carol-o-come-all-ye': 'John Francis Wade', 'carol-jingle-bells': 'James Lord Pierpont',
 'carol-away-in-a-manger': 'James R. Murray', 'carol-o-little-town': 'Lewis H. Redner', 'carol-we-three-kings': 'John Henry Hopkins Jr.',
 'carol-it-came-upon': 'Richard Storrs Willis', 'carol-carol-of-the-bells': 'Mykola Leontovych', 'carol-bleak-midwinter': 'Gustav Holst',
 'carol-angels-from-realms': 'Henry Smart', 'carol-once-in-royal': 'Henry J. Gauntlett', 'carol-up-on-the-housetop': 'Benjamin Hanby',
 'carol-what-child': 'Traditional (Greensleeves)', 'carol-auld-lang-syne': 'Traditional (Scottish)',
 'hymn-amazing-grace': 'Traditional (American)', 'hymn-be-thou-my-vision': 'Traditional (Irish)', 'hymn-it-is-well': 'Philip P. Bliss',
 'hymn-holy-holy': 'John B. Dykes', 'hymn-abide-with-me': 'William H. Monk', 'hymn-nearer-my-god': 'Lowell Mason', 'hymn-rock-of-ages': 'Thomas Hastings',
 'hymn-what-a-friend': 'Charles C. Converse', 'hymn-come-thou-fount': 'Traditional (American)', 'hymn-in-the-garden': 'C. Austin Miles',
 'hymn-blessed-assurance': 'Phoebe Knapp', 'hymn-a-mighty-fortress': 'Martin Luther', 'hymn-all-creatures': 'Traditional (German)',
 'hymn-jesus-loves-me': 'William B. Bradbury', 'hymn-shall-we-gather': 'Robert Lowry', 'hymn-softly-tenderly': 'Will L. Thompson',
 'hymn-when-the-saints': 'Traditional', 'hymn-battle-hymn': 'William Steffe', 'hymn-doxology': 'Louis Bourgeois', 'hymn-joyful-joyful': 'Ludwig van Beethoven',
 'hymn-crown-him': 'George J. Elvey', 'hymn-o-for-a-thousand': 'Carl G. Gläser', 'hymn-love-divine': 'John Zundel', 'hymn-eternal-father': 'John B. Dykes',
 'hymn-morning-has-broken': 'Traditional (Gaelic)', 'hymn-simple-gifts': 'Joseph Brackett', 'hymn-sweet-by-and-by': 'Joseph P. Webster',
 'hymn-there-is-power': 'Lewis E. Jones', 'hymn-are-you-washed': 'Anthony J. Showalter', 'hymn-i-need-thee': 'Robert Lowry', 'hymn-jerusalem': 'Hubert Parry',
 'hymn-i-vow-to-thee': 'Gustav Holst', 'hymn-onward': 'Arthur Sullivan', 'hymn-the-church-one': 'Samuel S. Wesley', 'hymn-all-hail': 'Oliver Holden',
 'hymn-when-i-survey': 'Lowell Mason', 'hymn-sometimes-feel': 'Spiritual (arr. Harry T. Burleigh)',
 'folk-o-sole-mio': 'Eduardo di Capua', 'folk-santa-lucia': 'Teodoro Cottrau', 'folk-funiculi': 'Luigi Denza', 'folk-torna-surriento': 'Ernesto De Curtis',
 'folk-la-paloma': 'Sebastián Yradier', 'folk-la-cumparsita': 'Gerardo Matos Rodríguez', 'folk-el-choclo': 'Ángel Villoldo', 'folk-estrellita': 'Manuel M. Ponce',
 'folk-lorelei': 'Friedrich Silcher', 'folk-oh-tannenbaum': 'Samuel Cohen', 'folk-kalinka': 'Ivan Larionov', 'folk-dark-eyes': 'Florian Hermann',
 'folk-home-on-the-range': 'Daniel E. Kelley', 'folk-clementine': 'Traditional (American)', 'folk-kojo-no-tsuki': 'Rentarō Taki', 'folk-furusato': 'Teiichi Okano',
 'folk-nkosi': 'Enoch Sontonga', 'folk-korobeiniki': 'Traditional (Russian)', 'folk-ievan-polkka': 'Traditional (Finnish)', 'folk-sakura': 'Traditional (Japanese)',
 'folk-arirang': 'Traditional (Korean)', 'folk-mo-li-hua': 'Traditional (Chinese)', 'folk-hava-nagila': 'Traditional (Jewish)', 'folk-bella-ciao': 'Traditional (Italian)',
 'folk-greensleeves': 'Traditional (English)', 'folk-danny-boy': 'Traditional (Irish)', 'folk-scarborough-fair': 'Traditional (English)',
 'kids-happy-birthday': 'Mildred J. Hill and Patty Hill', 'kids-chopsticks': 'Euphemia Allen',
 'pop-take-me-out': 'Albert Von Tilzer', 'pop-let-me-call-you-sweetheart': 'Leo Friedman', 'pop-daisy-bell': 'Harry Dacre', 'pop-after-the-ball': 'Charles K. Harris',
 'pop-in-the-good-old-summertime': 'George Evans', 'pop-meet-me-st-louis': 'Kerry Mills', 'pop-give-my-regards': 'George M. Cohan', 'pop-yankee-doodle-boy': 'George M. Cohan',
 'pop-grand-old-flag': 'George M. Cohan', 'pop-over-there': 'George M. Cohan', 'pop-silvery-moon': 'Gus Edwards', 'pop-old-mill-stream': 'Tell Taylor',
 'pop-irish-eyes': 'Ernest R. Ball', 'pop-wild-irish-rose': 'Chauncey Olcott', 'pop-bill-bailey': 'Hughie Cannon', 'pop-the-sidewalks': 'Charles Lawlor and James W. Blake',
 'pop-charleston': 'James P. Johnson', 'pop-aura-lee': 'George R. Poulton', 'pop-grandfathers-clock': 'Henry Clay Work', 'pop-the-band-played-on': 'Charles B. Ward',
 'pop-star-spangled': 'John Stafford Smith', 'pop-america-beautiful': 'Samuel A. Ward', 'pop-my-country': 'Traditional', 'pop-marine-hymn': 'Traditional (after Offenbach)',
 'pop-anchors-aweigh': 'Charles A. Zimmermann', 'pop-the-caissons': 'Patrick Gilmore', 'pop-yellow-rose': 'Traditional (American)', 'pop-in-the-shade': 'Egbert Van Alstyne',
 'pop-oh-you-beautiful-doll': 'Nat Ayer', 'pop-carolina-in-the-morning': 'Felix Powell', 'pop-its-a-long-way': 'Jack Judge', 'pop-keep-the-home-fires': 'Ivor Novello',
 'pop-hello-dolly-not': 'Alexander Muir', 'pop-o-canada': 'Calixa Lavallée', 'pop-la-marseillaise': 'Claude-Joseph Rouget de Lisle', 'pop-god-save': 'Traditional',
 'pop-rule-britannia': 'Thomas Arne', 'pop-the-entertainer-2': 'Euday L. Bowman', 'pop-dill-pickles': 'Charles L. Johnson', 'pop-black-and-white-rag': 'George Botsford',
 'pop-grizzly-bear': 'James Scott', 'pop-climax-rag': 'James Scott', 'pop-great-scott': 'James Scott', 'pop-carolina-shout': 'James P. Johnson',
 'pop-whistling-rufus': 'Kerry Mills', 'pop-hello-ma-baby': 'Abe Holzmann', 'pop-st-louis-tickle': 'Barney and Seymour', 'pop-limehouse-not': 'Neil Moret',
}
DEFAULT = {'carol': 'Traditional', 'hymn': 'Traditional', 'folk': 'Traditional', 'children': 'Traditional', 'americana': 'Traditional'}
SPIRITUAL = {'hymn-swing-low', 'hymn-wade-in-the-water', 'hymn-go-down-moses', 'hymn-deep-river', 'hymn-nobody-knows', 'hymn-were-you-there', 'hymn-this-little-light',
             'hymn-whole-world', 'hymn-michael-row', 'hymn-down-to-the-river', 'hymn-steal-away', 'hymn-were-climbing', 'hymn-there-is-a-balm', 'hymn-i-surrender'}
