const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),{JSDOM}=require('jsdom');
const dom=new JSDOM(''),ctx={window:{},DOMParser:dom.window.DOMParser,XMLSerializer:dom.window.XMLSerializer};vm.runInNewContext(fs.readFileSync('site/piano-import-engine.js','utf8'),ctx);const E=ctx.window.PianoImportEngine,fixture=fs.readFileSync('tests/fixtures/import-piano.musicxml','utf8');
const note=(step='C',extra='',duration=4)=>`<note><pitch><step>${step}</step><octave>4</octave></pitch><duration>${duration}</duration><type>whole</type>${extra}</note>`;
const measure=(body,extra='')=>`<measure><attributes><divisions>1</divisions><time><beats>4</beats><beat-type>4</beat-type></time></attributes>${body}${extra}</measure>`;
const score=body=>`<score-partwise><part-list><score-part id="P1"><part-name>Piano</part-name></score-part></part-list><part id="P1">${body}</part></score-partwise>`;
test('MusicXML imports both hands, chord pitches, all repeated measures and final ending',()=>{const p=E.parse(fixture);assert.equal(p.notes.length,16);assert.equal(p.totalBeats,20);assert.equal(p.writtenMeasures,3);assert.equal(p.performedMeasures,5);assert.equal(p.sourceFingering,true);assert.deepEqual([...new Set(p.notes.map(n=>n.hand))].sort(),['left','right']);assert.ok(p.notes.some(n=>n.beat===16&&n.midi===60));assert.equal(new dom.window.DOMParser().parseFromString(p.xml,'application/xml').querySelectorAll('measure').length,5);});
test('tied notes sustain across measures without requiring a second attack',()=>{const p=E.parse(score(measure(note('C','<tie type="start"/>'))+measure(note('C','<tie type="stop"/>'))));assert.equal(p.notes.length,1);assert.equal(p.notes[0].duration,8);assert.equal(p.heads.length,2);assert.equal(p.totalBeats,8);assert.throws(()=>E.parse(score(measure(note('C','<tie type="stop"/>')))),/contiguous start/);});
test('first and second endings unfold in performed order, not with a missing final section',()=>{const xml=score(measure('<barline location="left"><repeat direction="forward"/></barline>'+note('C'))+measure('<barline location="left"><ending number="1" type="start"/></barline>'+note('D'),'<barline location="right"><ending number="1" type="stop"/><repeat direction="backward"/></barline>')+measure('<barline location="left"><ending number="2" type="start"/></barline>'+note('E'),'<barline location="right"><ending number="2" type="stop"/></barline>'));const p=E.parse(xml);assert.deepEqual(Array.from(p.notes,n=>n.midi),[60,62,60,64]);assert.equal(p.totalBeats,16);});
test('successive implicit repeat starts do not repeat an earlier completed section',()=>{const p=E.parse(score(measure(note('C'),'<barline><repeat direction="backward"/></barline>')+measure(note('D'),'<barline><repeat direction="backward"/></barline>')));assert.deepEqual(Array.from(p.notes,n=>n.midi),[60,60,62,62]);});
test('pitch correction updates source and repeated playable notes while retaining fingering',()=>{const fixed=E.editPitch(fixture,0,'F#4'),p=E.parse(fixed);assert.equal(p.records[0].midi,66);assert.equal(p.notes.filter(n=>n.midi===66).length,2);assert.equal(p.sourceFingering,true);assert.equal(p.totalBeats,20);assert.throws(()=>E.editPitch(fixture,0,'wrong'),/Use a pitch/);});
test('leading/trailing rests are preserved, including the final silent measure',()=>{const p=E.parse(score(measure('<note><rest/><duration>1</duration></note>'+note('C','',1)+'<note><rest/><duration>2</duration></note>')+measure('<note><rest/><duration>4</duration></note>')));assert.equal(p.notes[0].beat,1);assert.equal(p.notes[0].duration,1);assert.equal(p.totalBeats,8);});
test('unsupported playback navigation, grace notes, malformed XML and entities fail explicitly',()=>{assert.throws(()=>E.parse(score(measure(note('C','<grace/>')))),/grace/);assert.throws(()=>E.parse(score(measure(note(),'<direction><sound dacapo="yes"/></direction>'))),/written out/);assert.throws(()=>E.parse('<!DOCTYPE x [<!ENTITY x "bad">]>'+fixture),/entity/);assert.throws(()=>E.parse('<score-partwise><broken>'),/malformed/);assert.throws(()=>E.parse(score(measure(note('C','',0)))),/valid duration/);});
test('compressed MusicXML resolves its declared root file and rejects inflated archives',async()=>{const fflate=require('../site/vendor/fflate-0.8.3.js');ctx.window.fflate=fflate;ctx.window.opensheetmusicdisplay={};ctx.document=dom.window.document;ctx.TextDecoder=TextDecoder;vm.runInNewContext(fs.readFileSync('site/piano-import-renderer.js','utf8'),ctx);const zip=fflate.zipSync({'META-INF/container.xml':new TextEncoder().encode('<container><rootfiles><rootfile full-path="score.musicxml"/></rootfiles></container>'),'score.musicxml':new TextEncoder().encode(fixture)});const file={name:'piece.mxl',size:zip.length,arrayBuffer:async()=>zip.buffer.slice(zip.byteOffset,zip.byteOffset+zip.byteLength)};const xml=await ctx.window.PianoImportRenderer.readXML(file);assert.equal(E.parse(xml).totalBeats,20);const huge=fflate.zipSync({'large.xml':new Uint8Array(17_000_000)});await assert.rejects(()=>ctx.window.PianoImportRenderer.readXML({name:'huge.mxl',size:huge.length,arrayBuffer:async()=>huge.buffer.slice(huge.byteOffset,huge.byteOffset+huge.byteLength)}),/too large/);});

test('unfolding retains one stable time signature and restores changing keys after repeats',()=>{const p=E.parse(fixture);const doc=new dom.window.DOMParser().parseFromString(p.xml,'application/xml');assert.equal(doc.querySelectorAll('time').length,1);assert.equal(doc.querySelectorAll('clef').length,2);const changed=fixture.replace('<measure number="2">','<measure number="2"><attributes><key><fifths>1</fifths></key></attributes>');const d=new dom.window.DOMParser().parseFromString(E.parse(changed).xml,'application/xml');assert.deepEqual([...d.querySelectorAll('fifths')].map(n=>n.textContent),['0','1','0','1']);});
