const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),{JSDOM}=require('jsdom');
const dom=new JSDOM(''),ctx={window:{},DOMParser:dom.window.DOMParser,XMLSerializer:dom.window.XMLSerializer};vm.runInNewContext(fs.readFileSync('site/piano-import-engine.js','utf8'),ctx);const E=ctx.window.PianoImportEngine,fixture=fs.readFileSync('tests/fixtures/import-piano.musicxml','utf8');
const note=(step='C',extra='',duration=4)=>`<note><pitch><step>${step}</step><octave>4</octave></pitch><duration>${duration}</duration><type>whole</type>${extra}</note>`;
const measure=(body,extra='')=>`<measure><attributes><divisions>1</divisions><time><beats>4</beats><beat-type>4</beat-type></time></attributes>${body}${extra}</measure>`;
const score=body=>`<score-partwise><part-list><score-part id="P1"><part-name>Piano</part-name></score-part></part-list><part id="P1">${body}</part></score-partwise>`;
test('MusicXML imports both hands, chord pitches, all repeated measures and final ending',()=>{const p=E.parse(fixture);assert.equal(p.notes.length,16);assert.equal(p.totalBeats,20);assert.equal(p.writtenMeasures,3);assert.equal(p.performedMeasures,5);assert.equal(p.sourceFingering,true);assert.deepEqual([...new Set(p.notes.map(n=>n.hand))].sort(),['left','right']);assert.ok(p.notes.some(n=>n.beat===16&&n.midi===60));assert.equal(new dom.window.DOMParser().parseFromString(p.xml,'application/xml').querySelectorAll('measure').length,5);});
test('tied notes sustain across measures without requiring a second attack',()=>{const p=E.parse(score(measure(note('C','<tie type="start"/>'))+measure(note('C','<tie type="stop"/>'))));assert.equal(p.notes.length,1);assert.equal(p.notes[0].duration,8);assert.equal(p.heads.length,2);assert.equal(p.totalBeats,8);assert.throws(()=>E.parse(score(measure(note('C','<tie type="stop"/>')))),/contiguous start/);});
test('first and second endings unfold in performed order, not with a missing final section',()=>{const xml=score(measure('<barline location="left"><repeat direction="forward"/></barline>'+note('C'))+measure('<barline location="left"><ending number="1" type="start"/></barline>'+note('D'),'<barline location="right"><ending number="1" type="stop"/><repeat direction="backward"/></barline>')+measure('<barline location="left"><ending number="2" type="start"/></barline>'+note('E'),'<barline location="right"><ending number="2" type="stop"/></barline>'));const p=E.parse(xml);assert.deepEqual(Array.from(p.notes,n=>n.midi),[60,62,60,64]);assert.equal(p.totalBeats,16);});
test('successive implicit repeat starts do not repeat an earlier completed section',()=>{const p=E.parse(score(measure(note('C'),'<barline><repeat direction="backward"/></barline>')+measure(note('D'),'<barline><repeat direction="backward"/></barline>')));assert.deepEqual(Array.from(p.notes,n=>n.midi),[60,60,62,62]);});
test('pitch correction updates source and repeated playable notes while retaining fingering',()=>{const fixed=E.editPitch(fixture,0,'F#4'),p=E.parse(fixed);assert.equal(p.records[0].midi,66);assert.equal(p.notes.filter(n=>n.midi===66).length,2);assert.equal(p.sourceFingering,true);assert.equal(p.totalBeats,20);assert.throws(()=>E.editPitch(fixture,0,'wrong'),/Use a pitch/);});
test('leading/trailing rests are preserved, including the final silent measure',()=>{const p=E.parse(score(measure('<note><rest/><duration>1</duration></note>'+note('C','',1)+'<note><rest/><duration>2</duration></note>')+measure('<note><rest/><duration>4</duration></note>')));assert.equal(p.notes[0].beat,1);assert.equal(p.notes[0].duration,1);assert.equal(p.totalBeats,8);});
test('unsupported playback navigation, orphaned grace notes, malformed XML and entities fail explicitly',()=>{assert.throws(()=>E.parse(score(measure(note('C','<grace/>')))),/grace/);assert.throws(()=>E.parse(score(measure(note(),'<direction><sound dacapo="yes"/></direction>'))),/written out/);assert.throws(()=>E.parse('<!DOCTYPE x [<!ENTITY x "bad">]>'+fixture),/entity/);assert.throws(()=>E.parse('<score-partwise><broken>'),/malformed/);assert.throws(()=>E.parse(score(measure(note('C','',0)))),/valid duration/);});
// A minimal .mxl writer: entries stored (method 0) or deflated (method 8), as notation programs export them.
function zip(entries){const zlib=require('node:zlib'),locals=[],centrals=[];let offset=0;for(const [name,content,deflate] of entries){const raw=Buffer.from(content),data=deflate?zlib.deflateRawSync(raw):raw,n=Buffer.from(name),h=Buffer.alloc(30);h.writeUInt32LE(0x04034b50,0);h.writeUInt16LE(20,4);h.writeUInt16LE(deflate?8:0,8);h.writeUInt32LE(data.length,18);h.writeUInt32LE(raw.length,22);h.writeUInt16LE(n.length,26);const c=Buffer.alloc(46);c.writeUInt32LE(0x02014b50,0);c.writeUInt16LE(20,4);c.writeUInt16LE(20,6);c.writeUInt16LE(deflate?8:0,10);c.writeUInt32LE(data.length,20);c.writeUInt32LE(raw.length,24);c.writeUInt16LE(n.length,28);c.writeUInt32LE(offset,42);locals.push(h,n,data);centrals.push(c,n);offset+=30+n.length+data.length;}const cd=Buffer.concat(centrals),e=Buffer.alloc(22);e.writeUInt32LE(0x06054b50,0);e.writeUInt16LE(entries.length,8);e.writeUInt16LE(entries.length,10);e.writeUInt32LE(cd.length,12);e.writeUInt32LE(offset,16);return Buffer.concat([...locals,cd,e]);}
const importer=()=>{const c={window:{PianoImportEngine:E},DOMParser:dom.window.DOMParser,XMLSerializer:dom.window.XMLSerializer,document:dom.window.document,TextDecoder,TextEncoder,Blob,Response,DecompressionStream};vm.runInNewContext(fs.readFileSync('site/piano-score-import.js','utf8'),c);return c.window.PianoScoreImport;};
const asFile=(name,buf)=>({name,size:buf.length,arrayBuffer:async()=>buf.buffer.slice(buf.byteOffset,buf.byteOffset+buf.byteLength)});
test('compressed MusicXML resolves its declared root file and rejects archives that inflate past 8 MB',async()=>{const I=importer();const mxl=zip([['META-INF/container.xml','<container><rootfiles><rootfile full-path="score.musicxml"/></rootfiles></container>',false],['decoy.xml','<x/>',false],['score.musicxml',fixture,true]]);const xml=await I.readMusicXML(asFile('piece.mxl',mxl));assert.equal(E.parse(xml).totalBeats,20);await assert.rejects(()=>I.readMusicXML(asFile('huge.mxl',zip([['large.xml',Buffer.alloc(17_000_000),true]]))),/too large/);});
test('My songs writes repeats out before engraving, and keeps scores it cannot unfold as printed',()=>{const I=importer();const unfolded=I.prepare(fixture);assert.equal(unfolded.unfolded,true);assert.ok(!unfolded.xml.includes('<repeat'));assert.ok(!unfolded.xml.includes('data-import-id'));assert.equal(new dom.window.DOMParser().parseFromString(unfolded.xml,'application/xml').querySelectorAll('measure').length,5);const coda=score(measure(note(),'<barline><repeat direction="backward"/></barline><direction><sound dacapo="yes"/></direction>'));const kept=I.prepare(coda);assert.equal(kept.unfolded,false);assert.equal(kept.repeatsAsWritten,true);assert.match(kept.problem,/written out/);assert.equal(kept.xml,coda);});
test('two single-staff piano parts become one part with right- and left-hand staves',()=>{const I=importer();const two=`<score-partwise><part-list><score-part id="P1"/><score-part id="P2"/></part-list><part id="P1"><measure><attributes><divisions>1</divisions><time><beats>4</beats><beat-type>4</beat-type></time><clef><sign>G</sign><line>2</line></clef></attributes>${note('E')}</measure></part><part id="P2"><measure><attributes><divisions>1</divisions><time><beats>4</beats><beat-type>4</beat-type></time><clef><sign>F</sign><line>4</line></clef></attributes><note><pitch><step>C</step><octave>3</octave></pitch><duration>4</duration><voice>1</voice><type>whole</type></note></measure></part></score-partwise>`;const doc=new dom.window.DOMParser().parseFromString(two,'application/xml');I.mergeParts(doc);assert.equal(doc.querySelectorAll('part').length,1);assert.equal(doc.querySelectorAll('score-part').length,1);assert.equal(doc.querySelector('staves').textContent,'2');assert.deepEqual([...doc.querySelectorAll('clef')].map(c=>c.getAttribute('number')),['1','2']);const low=[...doc.querySelectorAll('note')].find(n=>n.querySelector('step').textContent==='C');assert.equal(low.querySelector('staff').textContent,'2');assert.equal(low.querySelector('voice').textContent,'5');assert.equal(doc.querySelector('backup duration').textContent,'4');});

test('unfolding retains one stable time signature and restores changing keys after repeats',()=>{const p=E.parse(fixture);const doc=new dom.window.DOMParser().parseFromString(p.xml,'application/xml');assert.equal(doc.querySelectorAll('time').length,1);assert.equal(doc.querySelectorAll('clef').length,2);const changed=fixture.replace('<measure number="2">','<measure number="2"><attributes><key><fifths>1</fifths></key></attributes>');const d=new dom.window.DOMParser().parseFromString(E.parse(changed).xml,'application/xml');assert.deepEqual([...d.querySelectorAll('fifths')].map(n=>n.textContent),['0','1','0','1']);});

test('simple grace notes retain their written head and use a bounded playback lead-in',()=>{const xml=score(measure(note('C','',1)+note('D','<grace slash="yes"/>',0)+note('E','',3)));const p=E.parse(xml);assert.equal(p.graceCount,1);assert.equal(p.notes.length,3);assert.equal(p.totalBeats,4);assert.equal(p.notes[1].beat,.96);assert.equal(p.notes[1].duration,.04);assert.equal(p.notes[1].displayBeat,1);assert.ok(p.xml.includes('<grace'));const first=E.parse(score(measure(note('D','<grace/>',0)+note('E','',4))));assert.equal(first.notes[0].beat,0);assert.equal(first.notes[1].beat,.04);assert.equal(first.notes[1].beat+first.notes[1].duration,4);});
test('an overfull written bar fails rather than silently lengthening the piece',()=>{assert.throws(()=>E.parse(score(measure(note('C','',5)))),/Measure 1.*longer/);});
