"""Write site/piano-tempos.js: the marked tempo of every library score, in quarter notes per minute.

Usage: python3 scripts/build-marked-tempos.py

The practice player counts beats in quarter notes, so every tempo is converted to quarter notes.
For each folder in site/scores, in order of preference:
  1. the first printed metronome mark in original.mxl (<metronome>), else its first <sound tempo>;
  2. the first \\tempo with a number in original.ly or practice.ly, outside the \\midi block;
  3. the tempo of practice.midi (our own studies print no mark and are written for that tempo).
A score with none of these is left out; the progress code then uses a moderate default.
Values are clamped to the player's range, 30–200 BPM. Run it again after adding scores.
"""
import json, pathlib, re, zipfile

ROOT = pathlib.Path(__file__).resolve().parent.parent
SCORES, OUT = ROOT / 'site' / 'scores', ROOT / 'site' / 'piano-tempos.js'
UNIT = {'whole': 4, 'half': 2, 'quarter': 1, 'eighth': .5, '16th': .25}  # in quarter notes


def from_musicxml(path):
    try:
        z = zipfile.ZipFile(path)
        name = next(n for n in z.namelist() if n.endswith(('.xml', '.musicxml')) and not n.startswith('META-INF'))
        xml = z.read(name).decode('utf8', 'ignore')
    except Exception:
        return None
    m = re.search(r'<metronome[^>]*>\s*<beat-unit>(\w+)</beat-unit>\s*(<beat-unit-dot/>)?\s*<per-minute>([\d.]+)', xml)
    if m and m.group(1) in UNIT:
        return float(m.group(3)) * UNIT[m.group(1)] * (1.5 if m.group(2) else 1)
    s = re.search(r'<sound[^>]*\btempo="([\d.]+)"', xml)  # <sound tempo> is always in quarter notes
    return float(s.group(1)) if s else None


def from_lilypond(path):
    text = re.sub(r'\\midi\s*\{[^{}]*(\{[^{}]*\}[^{}]*)*\}', '', path.read_text(errors='ignore'))
    m = re.search(r'\\tempo\s*(?:"[^"]*"\s*)?(\d+)(\.?)\s*=\s*(\d+)', text)
    if not m:
        return None
    return float(m.group(3)) * 4 / int(m.group(1)) * (1.5 if m.group(2) else 1)


def from_midi(path):
    data = path.read_bytes()
    i = data.find(b'\xff\x51\x03')
    return 60e6 / int.from_bytes(data[i + 3:i + 6], 'big') if i >= 0 else None


def marked(folder):
    for name, read in (('original.mxl', from_musicxml), ('original.ly', from_lilypond), ('practice.ly', from_lilypond), ('practice.midi', from_midi)):
        if (folder / name).exists():
            bpm = read(folder / name)
            if bpm:
                return max(30, min(200, round(bpm)))
    return None


tempos = {f.name: bpm for f in sorted(SCORES.iterdir()) if f.is_dir() and (bpm := marked(f))}
OUT.write_text('/* Marked tempo of each library score in quarter notes per minute; generated by '
               'scripts/build-marked-tempos.py. */\nwindow.PianoTempos=' + json.dumps(tempos, separators=(',', ':')) + ';\n')
print(f'{len(tempos)} of {sum(1 for f in SCORES.iterdir() if f.is_dir())} scores have a tempo')
